/* Generated by Trae Work */

/**
 * 3×3 矩阵乘法：result[i][j] = Σ a[i][k] * b[k][j]
 * 用于第3章交换律验证区的实时计算
 */
export function multiply3x3(a: number[][], b: number[][]): number[][] {
  const result: number[][] = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
  ]
  for (let i = 0; i < 3; i++) {
    for (let j = 0; j < 3; j++) {
      for (let k = 0; k < 3; k++) {
        result[i][j] += a[i][k] * b[k][j]
      }
    }
  }
  return result
}

/**
 * 标准旋转矩阵（绕X/Y/Z轴右手定则 90°）
 * 这些矩阵来自视频讲座"用线性代数理解魔方"中的数学框架
 */
export const ROTATION_MATRICES: Record<string, number[][]> = {
  R:  [[1, 0, 0], [0, 0, -1], [0, 1, 0]],  // 绕X轴 +90°
  R2: [[1, 0, 0], [0, -1, 0], [0, 0, -1]], // 绕X轴 180°（R×R 的正确结果）
  U:  [[0, 0, 1], [0, 1, 0], [-1, 0, 0]],  // 绕Y轴 +90°（与 cubeLogic 中 U 操作一致）
  U2: [[-1, 0, 0], [0, 1, 0], [0, 0, -1]], // 绕Y轴 180°（U×U 的正确结果）
  F:  [[0, -1, 0], [1, 0, 0], [0, 0, 1]],  // 绕Z轴 +90°
  I:  [[1, 0, 0], [0, 1, 0], [0, 0, 1]],   // 单位矩阵
}

/**
 * 获取旋转矩阵的逆（转置即为逆，旋转矩阵是正交矩阵）
 * R' = R^T
 */
export function inverseMatrix(m: number[][]): number[][] {
  return [
    [m[0][0], m[1][0], m[2][0]],
    [m[0][1], m[1][1], m[2][1]],
    [m[0][2], m[1][2], m[2][2]],
  ]
}

/**
 * 矩阵转字符串（用于对比显示）
 */
export function matrixToString(m: number[][]): string {
  return m.map(row => row.join(' ')).join(' | ')
}

/**
 * 判断两个 3×3 矩阵是否相同
 */
export function matrixEqual(a: number[][], b: number[][]): boolean {
  for (let i = 0; i < 3; i++) {
    for (let j = 0; j < 3; j++) {
      if (a[i][j] !== b[i][j]) return false
    }
  }
  return true
}
