/* Generated by Trae Work */
import { create } from 'zustand';
import type { Cubie, Move } from '../types/cube';
import { createSolvedCube, applyMove, scrambleCube } from '../lib/cubeLogic';

/**
 * 魔方状态快照：存储某个时刻的方块数据
 * 用于 O(1) 撤销，避免重放全部历史
 */
interface Snapshot {
  cubies: Cubie[]
}

/**
 * 魔方状态 Store 接口
 * 管理魔方的方块数据、操作历史、动画状态和当前步骤
 */
interface CubeStore {
  /** 当前所有方块的颜色与位置数据 */
  cubies: Cubie[]
  /** 操作历史记录（用于撤销） */
  history: Move[]
  /** 中间状态快照（用于 O(1) 撤销） */
  snapshots: Snapshot[]
  /** 是否正在播放动画 */
  isAnimating: boolean
  /** 当前步骤索引（用于分步教学） */
  currentStep: number;

  /** 重置魔方到还原状态 */
  reset: () => void;
  /** 执行单个转动并加入历史 */
  applySingleMove: (move: Move) => void;
  /** 撤销上一步操作 */
  undo: () => void;
  /** 随机打乱魔方 n 步，或接受外部传入的确定结果（保证 3D 场景与 store 一致） */
  scramble: (nOrData: number | { cubies: Cubie[]; moves: Move[] }) => void;
  /** 设置动画播放状态 */
  setAnimating: (bool: boolean) => void;
}

/**
 * 魔方全局状态管理
 * 使用 Zustand 实现，组件通过 useCubeStore() 订阅
 */
export const useCubeStore = create<CubeStore>((set) => ({
  // ---- 初始状态 ----
  cubies: createSolvedCube(),
  snapshots: [{ cubies: createSolvedCube() }],
  history: [],
  isAnimating: false,
  currentStep: 0,

  /**
   * 重置：清空历史、回到还原状态、停止动画、步骤归零
   */
  reset: () =>
    set({
      cubies: createSolvedCube(),
      snapshots: [{ cubies: createSolvedCube() }],
      history: [],
      isAnimating: false,
      currentStep: 0,
    }),

  /**
   * 执行单个转动操作
   * 将操作应用到当前方块并追加到历史记录，同时保存快照
   */
  applySingleMove: (move: Move) =>
    set((state) => {
      const nextCubies = applyMove(state.cubies, move)
      return {
        cubies: nextCubies,
        snapshots: [...state.snapshots, { cubies: nextCubies }],
        history: [...state.history, move],
        currentStep: state.currentStep + 1,
      }
    }),

  /**
   * 撤销：直接回退到上一个快照（O(1)）
   * 利用 snapshots 数组，每次 undo 直接 pop 最后一项即可
   */
  undo: () =>
    set((state) => {
      if (state.snapshots.length === 0) return state;
      const snapshots = state.snapshots.slice(0, -1);
      return {
        cubies: snapshots.length > 0
          ? snapshots[snapshots.length - 1].cubies
          : createSolvedCube(),
        snapshots,
        history: state.history.slice(0, -1),
        currentStep: state.currentStep - 1,
      };
    }),

  /**
   * 打乱魔方：可用 n 自生成，也可从 3D 场景传入已算好的结果（保证一致性）
   */
  scramble: (nOrData: number | { cubies: Cubie[]; moves: Move[] }) => {
    // 从外部传入的确定结果（3D 场景算好的），直接使用
    if (typeof nOrData !== 'number') {
      const { cubies: finalCubies, moves } = nOrData
      const snapshots: Snapshot[] = [{ cubies: createSolvedCube() }]
      let acc = createSolvedCube()
      for (const m of moves) {
        acc = applyMove(acc, m)
        snapshots.push({ cubies: acc })
      }
      set({
        cubies: finalCubies,
        snapshots,
        history: moves,
        isAnimating: false,
        currentStep: moves.length,
      })
      return
    }
    // 自生成 n 步随机打乱
    const { cubies: finalCubies, moves } = scrambleCube(createSolvedCube(), nOrData)
    const snapshots: Snapshot[] = [{ cubies: createSolvedCube() }]
    let acc = createSolvedCube()
    for (const m of moves) {
      acc = applyMove(acc, m)
      snapshots.push({ cubies: acc })
    }
    set({
      cubies: finalCubies,
      snapshots,
      history: moves,
      isAnimating: false,
      currentStep: nOrData,
    })
  },

  /**
   * 设置动画状态（用于 3D 动画播放时锁定交互）
   */
  setAnimating: (bool: boolean) => set({ isAnimating: bool }),
}));
