/* Generated by Trae Work */
import { useState } from 'react'
import { Link } from 'react-router-dom'

const SECTIONS = [
  {
    id: 'boundary',
    title: '类比与真实的边界',
    body: (
      <>
        <p>本站用线性代数做类比科普，帮助理解魔方变换的行为逻辑。但需要明确以下几点：</p>
        <ul style={{ paddingLeft: '1.2rem', marginTop: '0.5rem' }}>
          <li>✅ 魔方操作确实对应矩阵运算中的一些性质：<strong>封闭性、结合律、单位元、逆元、非交换性</strong></li>
          <li>❌ 魔方不是线性空间：<strong>没有向量加法、没有数乘运算</strong></li>
          <li>🎯 魔方的严谨数学本质是<strong>置换群（鲁比克群）</strong>，其元素是贴纸位置的置换，而非欧几里得空间中的旋转</li>
        </ul>
        <p style={{ marginTop: '0.5rem' }}>本站的"向量""矩阵"等概念均用于类比解释，与严谨线性代数中的定义有所不同。为方便初学者建立直觉，我们用熟悉的线代语言搭建理解桥梁。</p>
      </>
    ),
  },
  {
    id: 'permutation',
    title: '置换群基础',
    body: (
      <>
        <p>魔方的每个状态是一个<strong>置换</strong>——把每个贴纸从原位置移到了新位置。</p>
        <ul style={{ paddingLeft: '1.2rem', marginTop: '0.5rem' }}>
          <li><strong>置换的循环：</strong>如果把若干方块依次换位并形成一个闭合的圈，就叫做循环。比如三个角块轮换一圈，就是一个3-循环</li>
          <li><strong>为什么不能单独交换两个块：</strong>因为每次转动总是偶数次两两交换，就像你不可能通过"每步走两格"来只移动一格</li>
          <li><strong>角块朝向的约束：</strong>所有角块的扭转角度之和必须是360°的倍数——这也是一个隐藏的规则</li>
        </ul>
      </>
    ),
  },
  {
    id: 'deep',
    title: '深度数学结论',
    body: (
      <>
        <ul style={{ paddingLeft: '1.2rem' }}>
          <li><strong>总状态数</strong>：魔方共有 43,252,003,274,489,856,000 种可能状态（约4.3×10¹⁹）。这个数字通过群论推导得出，不是枚举出来的。</li>
          <li style={{ marginTop: '0.5rem' }}><strong>上帝之数 = 20</strong>：任何打乱的魔方都可以在<strong>20步以内</strong>复原。2010年通过计算机穷举搜索证实。</li>
          <li style={{ marginTop: '0.5rem' }}><strong>子群与共轭类</strong>：魔方群具有丰富的子群结构，CFOP等速拧方法本质上就是在不同子群之间切换。</li>
        </ul>
      </>
    ),
  },
  {
    id: 'resources',
    title: '拓展资源',
    body: (
      <>
        <ul style={{ paddingLeft: '1.2rem' }}>
          <li>📖 <em>群论入门</em> — J.S. Milne（免费在线教材，英文）</li>
          <li>🎥 B站搜索 <em>"魔方 置换群"</em> — 多位UP主有通俗讲解</li>
          <li>📊 <em>魔方数学</em> — Wikipedia "Rubik's Cube group"</li>
          <li>🎬 YouTube <em>"How to Solve a Rubik's Cube with Group Theory"</em> — 适合初学者的群论入门视频</li>
        </ul>
      </>
    ),
  },
]

export default function Archive() {
  const [open, setOpen] = useState<string | null>(null)

  return (
    <>
      <div className="section">
        <div className="container" style={{ maxWidth: '860px', margin: '0 auto' }}>
          <h2 style={{ fontSize: '1.5rem', fontWeight: 700, marginBottom: '1.5rem' }}>
            📚 进阶数学档案馆
          </h2>

          <div className="accordion">
            {SECTIONS.map(s => (
              <div key={s.id}>
                <button
                  className={`accordion-header ${open === s.id ? 'open' : ''}`}
                  onClick={() => setOpen(open === s.id ? null : s.id)}
                >
                  {s.title}
                  <span className={`accordion-arrow ${open === s.id ? 'open' : ''}`}>▼</span>
                </button>
                <div className={`accordion-body ${open === s.id ? 'open' : ''}`}>
                  {s.body}
                </div>
              </div>
            ))}
          </div>

          <div style={{ marginTop: '2rem' }}>
            <Link to="/" className="btn btn-outline">← 返回首页</Link>
          </div>
        </div>
      </div>
    </>
  )
}
