/* Generated by Trae Work */
import { useParams, Link, useNavigate } from 'react-router-dom'
import { useRef, useEffect, useState, useCallback } from 'react'
import MatrixDisplay from '../components/MatrixDisplay'
import Cube3DView from '../components/cube3d/Cube3DView'
import type { Cube3DViewHandle } from '../components/cube3d/Cube3DView'
import {
  multiply3x3, ROTATION_MATRICES, inverseMatrix, matrixEqual,
} from '../lib/matrixMath'
import ReverseSequenceDemo from '../components/demo/ReverseSequenceDemo'
import ConjugateDemo from '../components/demo/ConjugateDemo'

/* ===== 章节数据结构 ===== */
interface ChapterData {
  title: string
  subtitle: string
  prev: string | null
  next: string | null
  keyPoints: string[]
  matrices?: { label: string; data: (number | string)[][] }[]
  demoHint: string
  analogy: string
}

/* ===== 记法 & 面名称映射（魔方新手友好） ===== */
/** 魔方记法 → 中文面名对照表 */
const FACE_NAME: Record<string, string> = {
  'R': 'R（右面顺时针）',  "R'": "R'（右面逆时针）",
  'L': 'L（左面顺时针）',  "L'": "L'（左面逆时针）",
  'U': 'U（上面顺时针）',  "U'": "U'（上面逆时针）",
  'D': 'D（底面顺时针）',  "D'": "D'（底面逆时针）",
  'F': 'F（前面顺时针）',  "F'": "F'（前面逆时针）",
  'B': 'B（后面顺时针）',  "B'": "B'（后面逆时针）",
}

/* ===== 章节颜色映射 ===== */
const CHAPTER_COLORS: Record<string, string> = {
  intro: '#3B82F6', matrix: '#10B981', compose: '#F59E0B',
  inverse: '#8B5CF6', invariant: '#06B6D4', solve: '#EF4444',
}

/* ===== 章节要点摘要 ===== */
const CHAPTER_SUMMARY: Record<string, string[]> = {
  intro: ['状态 = 向量', '26 块各有位置', '还原态 = 基准向量'],
  matrix: ['转动 = 旋转矩阵', 'R = 绕X轴90°', '矩阵不满足交换律'],
  compose: ['R·U ≠ U·R', '顺序影响结果', '矩阵乘法 ≠ 魔方操作可交换'],
  inverse: ['逆操作 = 逆矩阵', '(A·B)⁻¹ = B⁻¹·A⁻¹', '后做的先撤销'],
  invariant: ['中心块不动', '奇偶性守恒', '不可能只换两角'],
  solve: ['逆序撤销（初级）', '共轭变换（中级）', '交换子（高级）'],
}

/* ===== 第3章专属：交换律验证区配置 ===== */
const VERIFY_OPTIONS = ['R', "R'", 'U', "U'", 'F', "F'"] as const
type VerifyOption = typeof VERIFY_OPTIONS[number]

/** 将选择映射为可显示矩阵 */
function optionToMatrix(opt: VerifyOption): number[][] {
  const face = opt[0] // R/U/F
  const prime = opt.length > 1 // 是否有 '
  const m = ROTATION_MATRICES[face]
  return prime ? inverseMatrix(m) : m
}

/* ===== 六章内容数据 ===== */
const CHAPTER_CONTENT: Record<string, ChapterData> = {

  intro: {
    title: '魔方状态 = 向量',
    subtitle: '把魔方的当前排列看作一个高维状态向量',
    prev: null, next: 'matrix',
    keyPoints: [
      '一个魔方有 26 个小块（3×3×3 去掉中心），每个块有自己的位置和朝向',
      '如果把所有块的位置信息排成一列，就得到了一个"状态向量"',
      '就像线性代数里用向量表示点的空间位置，这里我们用向量表示魔方的整体状态',
      '还原状态是一个特殊的"基准向量"，所有其他状态都是它的变换结果',
    ],
    demoHint: '尝试点击右面（R面），用左键（逆时针）和右键（顺时针）分别转动，观察魔方状态变化',
    analogy: '类比：在平面上，一个点 (x, y) 是一个二维向量。魔方状态可以理解为 26 个方块在三维空间中的排列组合——一个高维"配置向量"。',
  },

  matrix: {
    title: '单次转动 = 变换矩阵',
    subtitle: '拧一层面就是对状态向量做一次线性变换',
    prev: 'intro', next: 'compose',
    keyPoints: [
      '魔方的每一次转动，本质上是对选定层上所有方块位置和朝向的重新排列',
      '在数学上，我们可以用 3×3 旋转矩阵描述方块坐标的变换——它保持长度和角度不变（注：这是简化类比，魔方操作的严谨本质是置换群，详见数学档案馆）',
      '右面顺时针转（R）就是把右层 8 个方块沿 X 轴旋转 90°',
      '重点：不同的面转动对应不同的变换矩阵，矩阵运算不满足交换律',
    ],
    matrices: [
      {
        label: 'R 面转动对应的旋转矩阵（绕X轴+90°）',
        data: [[1, 0, 0], [0, 0, -1], [0, 1, 0]],
      },
    ],
    demoHint: '将鼠标移到魔方右面上，左键点击=逆时针，右键点击=顺时针',
    analogy: '类比：在二维平面上，旋转矩阵 [[cosθ,-sinθ],[sinθ,cosθ]] 把向量旋转 θ 度。魔方的面转动也是类似的旋转变换，作用在三维方块上。',
  },

  compose: {
    title: '连续转动 = 矩阵乘法',
    subtitle: 'R×U ≠ U×R — 矩阵乘法不满足交换律',
    prev: 'matrix', next: 'inverse',
    keyPoints: [
      '先做 R 再做 U，整体效果等价于两个矩阵相乘：R × U',
      '反过来先 U 后 R，就是 U × R',
      '亲手计算就会发现：R × U ≠ U × R！矩阵乘法不满足交换律',
      '这就是为什么魔方操作顺序不能随便换 —— 对应的数学原理',
    ],
    demoHint: '鼠标左键点击面 = 逆时针旋转 | 右键点击面 = 顺时针旋转 | 空白处拖拽 = 旋转视角',
    analogy: '类比：生活中"先穿袜子再穿鞋"和"先穿鞋再穿袜子"结果是完全不同的。魔方的层转动也是如此——顺序决定最终状态。矩阵乘积 R×U ≠ U×R 就是这句话的数学表达。',
  },

  inverse: {
    title: '反向转动 = 逆矩阵',
    subtitle: 'R×R⁻¹=I，逆序撤销：(R·U)⁻¹=U⁻¹·R⁻¹',
    prev: 'compose', next: 'invariant',
    keyPoints: [
      '如果 R 是顺时针转 90°，那么 R\' 就是逆时针转 90° — 在数学上 R × R\' = I',
      '这就是"逆矩阵"的核心：存在一个操作让变换"撤销"',
      '(R·U)⁻¹ = U⁻¹·R⁻¹ — "后做的先撤销、先做的后撤销"',
      '复原魔方的核心：找到打乱序列的逆序列（逆序），反向操作即可还原',
    ],
    demoHint: '点击下方"撤销一步"按钮，观察逆操作逐步将魔方还原',
    analogy: '类比：如果你先穿上衣再穿裤子，脱的时候要先脱裤子再脱上衣——逆序法则就是"后做的先撤销，先做的后撤销"。数学上：(R·U)⁻¹ = U⁻¹·R⁻¹。',
  },

  invariant: {
    title: '守恒约束 = 不变量',
    subtitle: '某些东西在魔方转动中永远不会改变',
    prev: 'inverse', next: 'solve',
    keyPoints: [
      '在魔方中，某些性质在任意合法操作下都保持不变（称为"不变量"）',
      '例如：6 个中心块的相对位置永远不变（对 3 阶魔方而言）',
      '更深层的约束：角块排列的奇偶性和棱块排列的奇偶性始终相同——所以不可能只交换两个角块而其他块不变',
      '这类似正交矩阵的行列式满足 det(A)·det(B) = det(AB)：乘积关系恒成立。魔方中角块奇偶性 × 棱块奇偶性恒为偶（+1），所以不可能只交换两个角块而其他块不变',
    ],
    demoHint: '尝试打乱魔方，观察中心块的位置是否始终不变',
    analogy: '类比：正交矩阵的行列式满足 det(A)·det(B) = det(AB)，这个乘积关系永远不变。魔方也有不变量：任何合法操作下，角块排列的奇偶性和棱块排列的奇偶性始终相同（两者乘积恒为偶），所以不可能只交换两个角块而其他一切不动。',
  },

  solve: {
    title: '复原方法：抵消法',
    subtitle: '零公式自主还原的数学框架',
    prev: 'invariant', next: null,
    keyPoints: [
      '复原魔方的本质：找到一系列操作的逆操作，按逆序执行',
      '核心工具（初级）——逆序撤销：(A·B·C)⁻¹ = C⁻¹·B⁻¹·A⁻¹，后做的先撤销。Tutorial 角块部分在教这个',
      '核心工具（中级）——共轭变换：P·A·P\' 先搬到操作层→执行→搬回来。Tutorial 棱块部分在教这个',
      '核心工具（高级）——交换子 [X, Y] = X·Y·X\'·Y\'：只产生 3-循环（通常影响 3 个角块和 3 个棱块），不破坏已复原部分。后续探索',
      '下面的引导将带你亲手用逆序撤销和共轭变换复原角块和棱块',
    ],
    matrices: [],
    demoHint: '点击下方"开始引导"按钮，进入交互式复原引导',
    analogy: '类比：复原魔方就像解方程组——每一步"消元"只处理一个未知数，不破坏已经求解的变量。',
  },
}

/* ==================================================================== */
/*  章节编号映射                                                         */
/* ==================================================================== */
const CHAPTER_NUM: Record<string, number> = {
  intro: 1, matrix: 2, compose: 3, inverse: 4, invariant: 5, solve: 6,
}

/* ===== 表格基础样式（内联，第1章方向指数卡用） ===== */
const thStyle: React.CSSProperties = {
  padding: '0.4rem 0.6rem', textAlign: 'left',
  borderBottom: '2px solid var(--rule)', fontWeight: 700,
}
const tdStyle: React.CSSProperties = {
  padding: '0.35rem 0.6rem', borderBottom: '1px solid var(--rule)',
}

/* ============================ 第1章专属：方向指数说明卡 ============================ */
function DirectionIndexCard() {
  return (
    <div className="card" style={{ marginBottom: '1rem' }}>
      <h3 style={{ fontSize: '0.9rem', fontWeight: 700, marginBottom: '0.8rem' }}>
        方向指数编码
      </h3>
      <p style={{ fontSize: '0.8rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
        每个小块的位置用 3 个数字编码（H K L），取值为 1、0 或 -1：
      </p>
      <table style={{
        width: '100%', fontSize: '0.82rem', borderCollapse: 'collapse',
      }}>
        <thead>
          <tr style={{ background: 'var(--bg2)' }}>
            <th style={thStyle}>小块类型</th>
            <th style={thStyle}>方向指数</th>
            <th style={thStyle}>数量</th>
            <th style={thStyle}>说明</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td style={tdStyle}>角块</td>
            <td style={{ ...tdStyle, fontFamily: 'monospace' }}>(1, 1, 1)</td>
            <td style={tdStyle}>8</td>
            <td style={tdStyle}>3个面都有颜色，位于立方体角落</td>
          </tr>
          <tr>
            <td style={tdStyle}>棱块</td>
            <td style={{ ...tdStyle, fontFamily: 'monospace' }}>(1, 1, 0)</td>
            <td style={tdStyle}>12</td>
            <td style={tdStyle}>2个面有颜色，位于棱上</td>
          </tr>
          <tr>
            <td style={tdStyle}>心块</td>
            <td style={{ ...tdStyle, fontFamily: 'monospace' }}>(1, 0, 0)</td>
            <td style={tdStyle}>6</td>
            <td style={tdStyle}>1个面有颜色，位于面中心</td>
          </tr>
        </tbody>
      </table>
      <p style={{
        fontSize: '0.75rem', color: 'var(--muted)', marginTop: '0.6rem',
      }}>
        1、0、-1 三个数排列组合共 27 种，去掉 (0,0,0) 中心点 = 26 个方块，一个不多一个不少
      </p>
    </div>
  )
}

/* ============================ 自测题组件 ============================ */

/** 通用自测题选项组件 */
function QuizOptions({ options, explanation }: {
  options: { label: string; correct: boolean }[]
  explanation: string
}) {
  const [selected, setSelected] = useState<number | null>(null)

  return (
    <div>
      {options.map((opt, i) => (
        <button
          key={i}
          onClick={() => setSelected(i)}
          style={{
            display: 'block', width: '100%', textAlign: 'left',
            padding: '0.4rem 0.8rem', marginBottom: '0.4rem',
            borderRadius: '6px', border: '1px solid var(--rule)',
            background: selected === i
              ? opt.correct ? '#dcfce7' : '#fee2e2'
              : 'var(--bg)',
            fontSize: '0.82rem',
            cursor: 'pointer',
          }}
        >
          {opt.label}
          {selected === i && (
            <span style={{ marginLeft: '0.5rem' }}>
              {opt.correct ? '✅' : '❌'}
            </span>
          )}
        </button>
      ))}
      {selected !== null && (
        <p style={{
          marginTop: '0.6rem', padding: '0.6rem',
          background: options[selected].correct ? '#dcfce7' : '#fef3c7',
          borderRadius: '6px', fontSize: '0.8rem',
        }}>
          {options[selected].correct ? '🎉 ' : '💡 '}
          {explanation}
        </p>
      )}
    </div>
  )
}

/* ============================ 第3章专属：交换律验证区 ============================ */

interface ComposeVerifyProps {
  leftCubeRef: React.RefObject<Cube3DViewHandle | null>
  rightCubeRef: React.RefObject<Cube3DViewHandle | null>
}

/** 第3章：交换律验证区（双魔方并排对比） */
function ComposeVerify({ leftCubeRef, rightCubeRef }: ComposeVerifyProps) {
  const [step1, setStep1] = useState<VerifyOption>('R')
  const [step2, setStep2] = useState<VerifyOption>('U')
  const [resultAB, setResultAB] = useState<number[][] | null>(null)
  const [resultBA, setResultBA] = useState<number[][] | null>(null)
  const [compared, setCompared] = useState(false)

  /** 执行对比：双魔方同时演示，左=①→②，右=②→① */
  const handleCompare = useCallback(() => {
    const m1 = optionToMatrix(step1)
    const m2 = optionToMatrix(step2)
    const ab = multiply3x3(m1, m2)
    const ba = multiply3x3(m2, m1)
    setResultAB(ab)
    setResultBA(ba)
    setCompared(true)

    // 双魔方同时重置
    leftCubeRef.current?.reset()
    rightCubeRef.current?.reset()

    // 先演示左边（①→②），再演示右边（②→①）
    setTimeout(() => {
      // 左：① → ②
      leftCubeRef.current?.executeMove(step1)
      setTimeout(() => leftCubeRef.current?.executeMove(step2), 350)

      // 等左边演示完再开始右边
      setTimeout(() => {
        rightCubeRef.current?.executeMove(step2)
        setTimeout(() => rightCubeRef.current?.executeMove(step1), 350)
      }, 1200)
    }, 500)
  }, [step1, step2, leftCubeRef, rightCubeRef])

  const same = resultAB && resultBA ? matrixEqual(resultAB, resultBA) : null

  return (
    <div className="card" style={{ marginBottom: '1rem' }}>
      <h3 style={{ fontSize: '0.9rem', fontWeight: 700, marginBottom: '0.8rem' }}>
        交换律验证区
      </h3>
      <p style={{ fontSize: '0.8rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
        选择两个操作，左右两个魔方同时演示不同顺序 —— 看最终结果是否一致。
      </p>

      {/* 操作选择器 */}
      <div style={{
        display: 'flex', alignItems: 'center', gap: '0.5rem', flexWrap: 'wrap',
        marginBottom: '0.8rem',
      }}>
        <span style={{ fontSize: '0.85rem', fontWeight: 600 }}>操作 ①</span>
        <select
          value={step1}
          onChange={(e) => { setStep1(e.target.value as VerifyOption); setCompared(false) }}
          style={{
            padding: '0.3rem 0.5rem', borderRadius: '6px',
            border: '1px solid var(--rule)', fontSize: '0.85rem',
            fontFamily: 'monospace', background: '#fff',
          }}
        >
          {VERIFY_OPTIONS.map((o) => <option key={o} value={o}>{FACE_NAME[o]}</option>)}
        </select>
        <span style={{ fontSize: '0.85rem', fontWeight: 600 }}>操作 ②</span>
        <select
          value={step2}
          onChange={(e) => { setStep2(e.target.value as VerifyOption); setCompared(false) }}
          style={{
            padding: '0.3rem 0.5rem', borderRadius: '6px',
            border: '1px solid var(--rule)', fontSize: '0.85rem',
            fontFamily: 'monospace', background: '#fff',
          }}
        >
          {VERIFY_OPTIONS.map((o) => <option key={o} value={o}>{FACE_NAME[o]}</option>)}
        </select>
      </div>

      <button className="btn btn-primary" style={{ fontSize: '0.82rem', marginBottom: '0.8rem' }} onClick={handleCompare}>
        执行并对比
      </button>

      {/* 结果展示 */}
      {compared && resultAB && resultBA && (
        <div>
          <div style={{
            marginBottom: '0.8rem', padding: '0.4rem 0.8rem', borderRadius: '6px',
            fontWeight: 700, fontSize: '0.88rem',
            background: same ? '#DCFCE7' : '#FEE2E2',
            color: same ? '#16A34A' : '#DC2626',
          }}>
            结果：{same ? '相同 ✓（极少数情况）' : '不同 ✗（绝大多数情况）'}
          </div>

          {/* 矩阵对比 */}
          <div style={{
            display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.8rem',
          }}>
            <div style={{ textAlign: 'center' }}>
              <p style={{ fontSize: '0.72rem', color: 'var(--muted)', marginBottom: '0.3rem' }}>
                ①→②：{step1}×{step2}
              </p>
              <MatrixDisplay data={resultAB} />
            </div>
            <div style={{ textAlign: 'center' }}>
              <p style={{ fontSize: '0.72rem', color: 'var(--muted)', marginBottom: '0.3rem' }}>
                ②→①：{step2}×{step1}
              </p>
              <MatrixDisplay data={resultBA} />
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

/* ============================ 第4章专属：撤销演示 ============================ */

function InverseDemo({ cubeRef }: { cubeRef: React.RefObject<Cube3DViewHandle | null> }) {
  const PREDEFINED_MOVES = ['R', 'U', 'F', "U'"] as const
  const [remainingIdx, setRemainingIdx] = useState<number>(PREDEFINED_MOVES.length)
  const [initialized, setInitialized] = useState(false)
  const [done, setDone] = useState(false)

  // 初始化：打乱魔方
  useEffect(() => {
    if (!initialized && cubeRef.current) {
      const timer = setTimeout(() => {
        cubeRef.current?.reset()
        let delay = 500
        for (const move of PREDEFINED_MOVES) {
          setTimeout(() => cubeRef.current?.executeMove(move), delay)
          delay += 350
        }
        setTimeout(() => {
          setInitialized(true)
          setRemainingIdx(PREDEFINED_MOVES.length)
        }, delay)
      }, 600)
      return () => clearTimeout(timer)
    }
  }, [initialized])

  /** 撤销一步 */
  const handleUndoStep = useCallback(() => {
    if (remainingIdx <= 0 || !cubeRef.current) return
    const idx = remainingIdx - 1
    const move = PREDEFINED_MOVES[idx]
    const reverse = move.endsWith("'") ? move[0] : move + "'"
    cubeRef.current.undoMove(reverse)
    const newIdx = idx
    setRemainingIdx(newIdx)
    if (newIdx === 0) setDone(true)
  }, [remainingIdx])

  /** 重置演示 */
  const handleReset = useCallback(() => {
    cubeRef.current?.reset()
    setInitialized(false)
    setDone(false)
  }, [])

  const remaining = PREDEFINED_MOVES.slice(0, remainingIdx)

  return (
    <div className="card" style={{ marginBottom: '1rem' }}>
      <h3 style={{ fontSize: '0.9rem', fontWeight: 700, marginBottom: '0.6rem' }}>
        🔄 撤销演示
      </h3>
      <p style={{ fontSize: '0.8rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
        魔方已执行了 4 步操作。点击"撤销一步"，观察逆操作逐步还原。
      </p>

      {initialized && (
        <div style={{
          marginBottom: '0.8rem', padding: '0.4rem 0.8rem', borderRadius: '6px',
          background: done ? '#DCFCE7' : 'var(--bg2)',
          fontSize: '0.82rem',
        }}>
          {done ? (
            <span style={{ fontWeight: 700, color: '#16A34A' }}>🎉 还原成功！这就是逆矩阵的力量</span>
          ) : (
            <span>
              <strong>剩余操作：</strong>
              <span style={{ fontFamily: 'monospace', color: 'var(--accent)' }}>
                {remaining.length > 0 ? remaining.map(m => FACE_NAME[m] || m).join(' · ') : '（空）'}
              </span>
            </span>
          )}
        </div>
      )}

      <div style={{ display: 'flex', gap: '0.5rem' }}>
        <button
          className="btn btn-primary"
          style={{ fontSize: '0.82rem' }}
          onClick={handleUndoStep}
          disabled={!initialized || remainingIdx <= 0}
        >
          🔄 撤销一步
        </button>
        <button
          className="btn btn-outline"
          style={{ fontSize: '0.82rem' }}
          onClick={handleReset}
        >
          重置演示
        </button>
      </div>
    </div>
  )
}


/* ============================ 第5章专属：不变量观察器 ============================ */

function InvariantDemo({ cubeRef }: { cubeRef: React.RefObject<Cube3DViewHandle | null> }) {
  const [scrambled, setScrambled] = useState(false)
  const [count, setCount] = useState(0)
  const [showIllegal, setShowIllegal] = useState(false)

  const handleIllegalSwap = useCallback(() => { setShowIllegal(true) }, [])

  // 随机打乱：先重置再打乱 12 步，让用户观察中心块不动
  const handleScramble = useCallback(() => {
    cubeRef.current?.reset()
    setTimeout(() => cubeRef.current?.scramble(12), 300)
    setScrambled(true)
    setCount((c) => c + 1)
  }, [])

  // 重置为还原态
  const handleReset = useCallback(() => {
    cubeRef.current?.reset()
    setScrambled(false)
  }, [])

  return (
    <div className="card" style={{ marginBottom: '1rem', borderLeft: '4px solid var(--accent)' }}>
      <h3 style={{ fontSize: '0.9rem', fontWeight: 700, marginBottom: '0.6rem' }}>
        不变量观察器
      </h3>
      <p style={{ fontSize: '0.8rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
        多次点击"随机打乱"并观察：无论怎么转，
        <strong>6 个中心块的相对位置始终不变</strong>——
        红对着橙，蓝对着绿，白对着黄。这就是魔方的"不变量"。
      </p>

      {scrambled && count > 0 && (
        <div style={{
          marginBottom: '0.8rem', padding: '0.5rem 0.8rem', borderRadius: '6px',
          background: '#DCFCE7', fontSize: '0.82rem',
        }}>
          <span style={{ fontWeight: 700, color: '#16A34A' }}>
            已打乱 {count} 次
          </span>
          <span style={{ color: 'var(--ink2)', marginLeft: '0.4rem' }}>
            — 红橘相对、蓝绿相对、白黄相对，不变
          </span>
        </div>
      )}

      <div style={{ display: 'flex', gap: '0.5rem' }}>
        <button
          className="btn btn-primary"
          style={{ fontSize: '0.82rem' }}
          onClick={handleScramble}
        >
          随机打乱
        </button>
        <button
          className="btn btn-outline"
          style={{ fontSize: '0.82rem' }}
          onClick={handleReset}
        >
          重置
        </button>
        <button className="btn btn-outline" style={{ fontSize: '0.82rem', color: '#DC2626', borderColor: '#DC2626' }} onClick={handleIllegalSwap}>非法状态</button>
      </div>
      <div style={{ marginTop: '0.8rem', padding: '0.6rem 0.8rem', borderRadius: '6px', background: '#FEF3C7', borderLeft: '3px solid #F59E0B', fontSize: '0.8rem', color: 'var(--ink2)' }}>更深层的不变量：角块排列的奇偶性和棱块排列的奇偶性始终相同。因此不可能只交换两个角块而其他一切不动——这不是技术不够，是数学约束。</div>
      {showIllegal && (<div style={{ marginTop: '0.6rem', padding: '0.6rem 0.8rem', borderRadius: '6px', background: '#FEE2E2', fontSize: '0.82rem', color: '#DC2626' }}>这是一个<strong>数学上不可能</strong>的状态！只交换两个角块违反了奇偶性守恒——即使你拆散魔方重新组装也无法通过合法转动达到。</div>)}
    </div>
  )
}

/* ============================ 交换子动画演示组件 ============================ */
function CommutatorDemo({ cubeRef }: { cubeRef: React.RefObject<Cube3DViewHandle | null> }) {
  const MOVES = ['R', 'U', "R'", "U'"] as const
  const [step, setStep] = useState(0)
  const [running, setRunning] = useState(false)
  const [done, setDone] = useState(false)
  const handlePlay = useCallback(() => {
    if (running) return
    cubeRef.current?.reset()
    setStep(0); setDone(false); setRunning(true)
    let delay = 600
    for (let i = 0; i < MOVES.length; i++) {
      setTimeout(() => {
        cubeRef.current?.executeMove(MOVES[i])
        setStep(i + 1)
        if (i === MOVES.length - 1) { setDone(true); setRunning(false) }
      }, delay)
      delay += 1000
    }
  }, [running])
  const handleReset = useCallback(() => { cubeRef.current?.reset(); setStep(0); setDone(false); setRunning(false) }, [])
  return (
    <div className="card" style={{ marginBottom: '1rem', borderLeft: '4px solid #8B5CF6' }}>
      <h3 style={{ fontSize: '0.9rem', fontWeight: 700, marginBottom: '0.6rem' }}>交换子演示 [X, Y] = X·Y·X'·Y'</h3>
      <p style={{ fontSize: '0.8rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>点击播放交换子观察：R·U·R'·U' 只产生 3-循环（3 个角块和 3 个棱块各自轮换，其余不变）</p>
      <div style={{ display: 'flex', gap: '0.3rem', marginBottom: '0.8rem' }}>
        {MOVES.map((move, i) => (<div key={i} style={{ flex: 1, padding: '0.3rem', textAlign: 'center', borderRadius: '4px', fontSize: '0.78rem', fontFamily: 'monospace', background: step > i ? '#EDE9FE' : step === i && running ? '#FDE68A' : 'var(--bg2)', fontWeight: step > i ? 700 : 400, color: step > i ? '#7C3AED' : 'var(--ink2)' }}>{move}</div>))}
      </div>
      {done && <div style={{ marginBottom: '0.8rem', padding: '0.4rem 0.8rem', borderRadius: '6px', background: '#EDE9FE', fontSize: '0.82rem', color: '#7C3AED', fontWeight: 600 }}>交换子完成！只产生了 3-循环（3 角块 + 3 棱块各自轮换）</div>}
      <div style={{ display: 'flex', gap: '0.5rem' }}>
        <button className="btn btn-primary" style={{ fontSize: '0.82rem' }} onClick={handlePlay} disabled={running}>{running ? '播放中...' : '▶ 播放交换子'}</button>
        <button className="btn btn-outline" style={{ fontSize: '0.82rem' }} onClick={handleReset}>重置</button>
      </div>
    </div>
  )
}

/* ============================ 主组件 ============================ */


/* ============================ 第6节专属：Tab 演示面板 ============================ */
/** 右栏演示面板：用 tab 切换逆序撤销/共轭变换/交换子 */
function SolveDemoPanel({ cubeRef }: { cubeRef: React.RefObject<Cube3DViewHandle | null> }) {
  const [tab, setTab] = useState<'reverse' | 'conjugate' | 'commutator'>('reverse')
  const tabs = [
    { key: 'reverse' as const, label: '逆序撤销', icon: '🔄', color: '#10B981' },
    { key: 'conjugate' as const, label: '共轭变换', icon: '🍚', color: '#F59E0B' },
    { key: 'commutator' as const, label: '交换子', icon: '⚡', color: '#EF4444' },
  ]
  return (
    <div className="card" style={{ padding: '0', overflow: 'hidden' }}>
      {/* Tab 栏 */}
      <div style={{ display: 'flex', borderBottom: '2px solid var(--rule)' }}>
        {tabs.map((t) => (
          <button
            key={t.key}
            onClick={() => setTab(t.key)}
            style={{
              flex: 1, padding: '0.5rem 0.3rem', fontSize: '0.78rem',
              fontWeight: tab === t.key ? 700 : 400,
              borderBottom: tab === t.key ? `3px solid ${t.color}` : '3px solid transparent',
              background: tab === t.key ? '#fff' : 'var(--bg2)',
              color: tab === t.key ? t.color : 'var(--ink2)',
              border: 'none', cursor: 'pointer',
              transition: 'all 0.2s ease',
            }}
          >
            {t.icon} {t.label}
          </button>
        ))}
      </div>
      {/* Tab 内容 */}
      <div style={{ padding: '0.8rem 1rem' }}>
        {tab === 'reverse' && <ReverseSequenceDemo cubeRef={cubeRef} />}
        {tab === 'conjugate' && <ConjugateDemo cubeRef={cubeRef} />}
        {tab === 'commutator' && <CommutatorDemo cubeRef={cubeRef} />}
      </div>
    </div>
  )
}

export default function Chapter() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const ch = id ? CHAPTER_CONTENT[id] : undefined
  const cubeRef = useRef<Cube3DViewHandle>(null)
  /** 第3章专用：左右两个魔方对比 */
  const leftCubeRef = useRef<Cube3DViewHandle>(null)
  const rightCubeRef = useRef<Cube3DViewHandle>(null)

  /* ---- 404 ---- */
  if (!ch) {
    return (
      <div className="section">
        <div className="container" style={{ textAlign: 'center', paddingTop: '3rem' }}>
          <h2 style={{ fontSize: '1.4rem', marginBottom: '0.8rem' }}>章节未找到</h2>
          <p style={{ color: 'var(--ink2)', marginBottom: '1.2rem' }}>「{id}」不是有效的章节编号。</p>
          <Link to="/" className="btn btn-primary">返回首页</Link>
        </div>
      </div>
    )
  }

  /* ---- 第3章矩阵数据：2×2网格展示用 ---- */
  const composeMatrices = id === 'compose' ? [
    { label: 'R 转动矩阵', data: ROTATION_MATRICES.R as unknown as (string | number)[][] },
    { label: 'U 转动矩阵', data: ROTATION_MATRICES.U as unknown as (string | number)[][] },
    { label: 'R × U =', data: multiply3x3(ROTATION_MATRICES.R, ROTATION_MATRICES.U) as unknown as (string | number)[][] },
    { label: 'U × R =', data: multiply3x3(ROTATION_MATRICES.U, ROTATION_MATRICES.R) as unknown as (string | number)[][] },
  ] : undefined

  /* ---- 第4章矩阵数据：去掉重复 ---- */
  const inverseMatrices = id === 'inverse' ? [
    { label: 'R⁻¹ 逆矩阵（逆时针90°）', data: inverseMatrix(ROTATION_MATRICES.R) as unknown as (string | number)[][] },
    { label: '验证：R × R⁻¹ = I（单位矩阵）', data: multiply3x3(ROTATION_MATRICES.R, inverseMatrix(ROTATION_MATRICES.R)) as unknown as (string | number)[][] },
    { label: '逆序法则：(R·U)⁻¹ = U⁻¹·R⁻¹ =', data: multiply3x3(inverseMatrix(ROTATION_MATRICES.U), inverseMatrix(ROTATION_MATRICES.R)) as unknown as (string | number)[][] },
  ] : undefined

  /* ---- 选择使用哪个矩阵数据集 ---- */
  const displayMatrices = id === 'compose' ? composeMatrices : id === 'inverse' ? inverseMatrices : ch.matrices

  return (
    <>
      <div className="section">
        <div className="container">
          {/* 章节标题 */}
          <h2 style={{ fontSize: '1.6rem', fontWeight: 700, marginBottom: '0.3rem', borderLeft: `5px solid ${CHAPTER_COLORS[id!]}`, paddingLeft: '0.8rem' }}>
            第 {CHAPTER_NUM[id!]} 节 &nbsp;{ch.title}
          </h2>
          <p style={{ fontSize: '0.95rem', color: 'var(--ink2)', marginBottom: '1.5rem' }}>
            {ch.subtitle}
          </p>
          {/* ===== 第6节专属：终章渐变横幅 ===== */}
          {id === 'solve' && (
            <div style={{
              marginBottom: '1.5rem',
              padding: '1.2rem 1.5rem',
              borderRadius: '12px',
              background: 'linear-gradient(135deg, #1E1B4B 0%, #3B0764 40%, #7F1D1D 100%)',
              color: '#fff',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.8rem', marginBottom: '0.6rem' }}>
                <span style={{ fontSize: '1.8rem' }}>🏆</span>
                <div>
                  <h3 style={{ fontSize: '1.1rem', fontWeight: 800, margin: 0, letterSpacing: '0.5px' }}>
                    终章挑战：把前面学的全部用上
                  </h3>
                  <p style={{ fontSize: '0.82rem', margin: '0.2rem 0 0 0', opacity: 0.85 }}>
                    这一节将串联全部知识点，从"看着公式还原"进化到"理解每一步为什么这样做"
                  </p>
                </div>
              </div>
              {/* 三个核心工具预览标签 */}
              <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
                {[
                  { label: '初级 · 逆序撤销', color: '#10B981', icon: '🔄' },
                  { label: '中级 · 共轭变换', color: '#F59E0B', icon: '🥪' },
                  { label: '高级 · 交换子', color: '#EF4444', icon: '⚡' },
                ].map((tool) => (
                  <div key={tool.label} style={{
                    display: 'flex', alignItems: 'center', gap: '0.3rem',
                    padding: '0.3rem 0.7rem', borderRadius: '20px',
                    background: 'rgba(255,255,255,0.15)',
                    fontSize: '0.78rem', fontWeight: 600,
                    border: `1px solid ${tool.color}40`,
                  }}>
                    <span>{tool.icon}</span>
                    <span>{tool.label}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* ===== 双栏布局 ===== */}
          <div className="two-col">
            {/* ===== 左侧：概念讲解区 ===== */}
            <div>
              {/* 本节要点 */}
              <div className="card" style={{ marginBottom: '1rem' }}>
                <h3 style={{ fontSize: '0.9rem', fontWeight: 700, marginBottom: '0.8rem', color: 'var(--accent)' }}>
                  本节要点
                </h3>
                <ul style={{ paddingLeft: '1.2rem', fontSize: '0.85rem', color: 'var(--ink2)', lineHeight: 1.8 }}>
                  {ch.keyPoints.map((point, i) => (
                    <li key={i} style={{ marginBottom: '0.4rem' }}>{point}</li>
                  ))}
                </ul>
              </div>

              {/* 第1章专属：方向指数说明卡 */}
              {id === 'intro' && <DirectionIndexCard />}

              {/* 第3章：矩阵2×2网格（与右侧验证区对应，平衡左右视觉） */}
              {id === 'compose' && composeMatrices && (
                <div className="card" style={{ marginBottom: '1rem' }}>
                  <h3 style={{ fontSize: '0.9rem', fontWeight: 700, marginBottom: '0.8rem' }}>
                    真实转动矩阵：魔方面操作对应的数学表达
                  </h3>
                  <div style={{
                    display: 'grid', gridTemplateColumns: '1fr 1fr',
                    gap: '0.6rem', marginBottom: '0.6rem',
                  }}>
                    {composeMatrices.map((m, i) => (
                      <div key={i} style={{
                        textAlign: 'center', padding: '0.5rem',
                        background: 'var(--bg2)', borderRadius: '8px',
                      }}>
                        <p style={{
                          fontSize: '0.72rem', color: 'var(--muted)',
                          marginBottom: '0.3rem', fontWeight: 600,
                        }}>
                          {m.label}
                        </p>
                        <MatrixDisplay data={m.data} />
                      </div>
                    ))}
                  </div>
                  <p style={{
                    textAlign: 'center', fontSize: '0.75rem',
                    color: 'var(--orange)', fontWeight: 600,
                  }}>
                    ⚠️ 两行结果不同！顺序很重要！
                  </p>
                  <p style={{
                    fontSize: '0.72rem', color: 'var(--muted)',
                    marginTop: '0.5rem', textAlign: 'center',
                  }}>
                    上排 = R×U，下排 = U×R —— 矩阵乘法不满足交换律
                  </p>
                </div>
              )}

              {/* 第4章：逆矩阵计算（与右侧撤销演示对应，平衡左右视觉） */}
              {id === 'inverse' && inverseMatrices && (
                <div className="card" style={{ marginBottom: '1rem' }}>
                  <h3 style={{ fontSize: '0.9rem', fontWeight: 700, marginBottom: '0.8rem' }}>
                    逆矩阵计算
                  </h3>
                  {inverseMatrices.map((m, i) => (
                    <div key={i} style={{ marginBottom: i < inverseMatrices.length - 1 ? '1rem' : 0 }}>
                      <p style={{ fontSize: '0.78rem', color: 'var(--muted)', marginBottom: '0.4rem' }}>
                        {m.label}
                      </p>
                      <MatrixDisplay data={m.data} />
                    </div>
                  ))}
                  <p style={{ fontSize: '0.78rem', color: 'var(--ink2)', marginTop: '0.6rem' }}>
                    也就是说：先拧R再拧U的撤销方法是——先撤销U（U⁻¹），再撤销R（R⁻¹），顺序反过来！
                  </p>
                </div>
              )}

              {/* 矩阵展示（仅非第3/4章） */}
              {id !== 'compose' && id !== 'inverse' && displayMatrices && displayMatrices.length > 0 && (
                <div className="card" style={{ marginBottom: '1rem' }}>
                  <h3 style={{ fontSize: '0.9rem', fontWeight: 700, marginBottom: '0.8rem' }}>
                    数学演示
                  </h3>
                  {displayMatrices.map((m, i) => (
                    <div key={i} style={{ marginBottom: i < displayMatrices.length - 1 ? '1rem' : 0 }}>
                      <p style={{ fontSize: '0.78rem', color: 'var(--muted)', marginBottom: '0.4rem' }}>
                        {m.label}
                      </p>
                      <MatrixDisplay data={m.data} />
                    </div>
                  ))}
                  {id === 'matrix' && (
                    <p style={{ fontSize: '0.75rem', color: 'var(--ink3)', marginTop: '0.5rem', fontStyle: 'italic' }}>
                      ※ 此处用 3×3 旋转矩阵做简化类比，描述单个方块坐标的变换。魔方操作实际上是对 20 个可动方块的整体置换，严谨数学框架见<a href="#/archive" style={{ color: 'var(--accent)' }}>数学档案馆</a>。
                    </p>
                  )}
                </div>
              )}

              {/* ===== 第6节专属：三大核心工具卡片网格 ===== */}
              {id === 'solve' && (
                <div style={{ marginBottom: '1rem' }}>
                  <h3 style={{ fontSize: '0.9rem', fontWeight: 700, marginBottom: '0.8rem', color: 'var(--accent)' }}>
                    复原工具箱：三个层次的数学工具
                  </h3>
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '0.6rem' }}>
                    {/* 初级：逆序撤销 */}
                    <div className="card" style={{ marginBottom: 0, borderLeft: '4px solid #10B981', padding: '0.8rem 1rem' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', marginBottom: '0.4rem' }}>
                        <span style={{ fontSize: '1rem' }}>🔄</span>
                        <span style={{ fontSize: '0.78rem', fontWeight: 700, color: '#10B981' }}>初级</span>
                      </div>
                      <p style={{ fontSize: '0.78rem', fontWeight: 600, marginBottom: '0.3rem' }}>逆序撤销</p>
                      <p style={{ fontSize: '0.72rem', color: 'var(--ink2)', lineHeight: 1.5, marginBottom: 0 }}>
                        (A·B·C)⁻¹ = C⁻¹·B⁻¹·A⁻¹
                      </p>
                      <p style={{ fontSize: '0.68rem', color: 'var(--muted)', lineHeight: 1.4, marginTop: '0.2rem' }}>
                        后做的先撤销，Tutorial 角块在教这个
                      </p>
                    </div>
                    {/* 中级：共轭变换 */}
                    <div className="card" style={{ marginBottom: 0, borderLeft: '4px solid #F59E0B', padding: '0.8rem 1rem' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', marginBottom: '0.4rem' }}>
                        <span style={{ fontSize: '1rem' }}>🥪</span>
                        <span style={{ fontSize: '0.78rem', fontWeight: 700, color: '#F59E0B' }}>中级</span>
                      </div>
                      <p style={{ fontSize: '0.78rem', fontWeight: 600, marginBottom: '0.3rem' }}>共轭变换</p>
                      <p style={{ fontSize: '0.72rem', color: 'var(--ink2)', lineHeight: 1.5, marginBottom: 0 }}>
                        P·A·P'：搬过去→执行→搬回来
                      </p>
                      <p style={{ fontSize: '0.68rem', color: 'var(--muted)', lineHeight: 1.4, marginTop: '0.2rem' }}>
                        精准手术式操作，Tutorial 棱块在教这个
                      </p>
                    </div>
                    {/* 高级：交换子 */}
                    <div className="card" style={{ marginBottom: 0, borderLeft: '4px solid #EF4444', padding: '0.8rem 1rem' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', marginBottom: '0.4rem' }}>
                        <span style={{ fontSize: '1rem' }}>⚡</span>
                        <span style={{ fontSize: '0.78rem', fontWeight: 700, color: '#EF4444' }}>高级</span>
                      </div>
                      <p style={{ fontSize: '0.78rem', fontWeight: 600, marginBottom: '0.3rem' }}>交换子</p>
                      <p style={{ fontSize: '0.72rem', color: 'var(--ink2)', lineHeight: 1.5, marginBottom: 0 }}>
                        [X,Y] = X·Y·X'·Y'：3-循环
                      </p>
                      <p style={{ fontSize: '0.68rem', color: 'var(--muted)', lineHeight: 1.4, marginTop: '0.2rem' }}>
                        3-循环（3角块+3棱块），不破坏其他，后续探索
                      </p>
                    </div>
                  </div>
                </div>
              )}

              {/* 第6节专属：CTA 引导按钮 */}
              {id === 'solve' && (
                <div style={{
                  marginBottom: '1rem', padding: '1rem 1.2rem',
                  borderRadius: '12px',
                  background: 'linear-gradient(135deg, #FEF3C7 0%, #FEE2E2 100%)',
                  border: '2px solid #F59E0B',
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
                    <span style={{ fontSize: '1.2rem' }}>🎯</span>
                    <span style={{ fontSize: '0.9rem', fontWeight: 700 }}>准备好了吗？开始引导复原</span>
                  </div>
                  <p style={{ fontSize: '0.78rem', color: 'var(--ink2)', marginBottom: '0.8rem', lineHeight: 1.5 }}>
                    白色十字已就位，你将亲手用逆序撤销复原角块、用共轭变换复原棱块。<br/>
                    完整路线：底面十字 → 角块 → 中层棱块 → 顶面（后续扩展）
                  </p>
                  <div style={{ fontSize: '0.72rem', color: 'var(--ink2)', marginBottom: '0.8rem', lineHeight: 1.6 }}>
                    <div style={{ marginBottom: '0.15rem' }}>✅ 白色十字（直觉操作）</div>
                    <div style={{ marginBottom: '0.15rem' }}>✅ 白色角块 — 逆序列法则（R' D' R D）</div>
                    <div style={{ marginBottom: '0.15rem' }}>✅ 中层棱块 — 共轭变换（U R U' R' U' F' U F）</div>
                    <div style={{ marginBottom: '0.15rem' }}>✅ 黄色十字 — 交换子（F R U R' U' F'）</div>
                    <div style={{ color: 'var(--muted)' }}>⬜ 黄面角位 / 归位 / 翻角</div>
                  </div>
                  <button
                    className="btn btn-primary"
                    style={{ fontSize: '0.9rem', width: '100%', padding: '0.7rem', fontWeight: 700 }}
                    onClick={() => navigate('/tutorial')}
                  >
                    🚀 开始交互式复原引导
                  </button>
                </div>
              )}


              {/* 比喻说明 */}
              <div className="analogy-note">
                <span style={{ fontWeight: 600, marginRight: '0.3rem' }}>比喻理解</span>
                <span>{ch.analogy}</span>
            </div>

            {/* 第3章专属：自测题 */}
            {id === 'compose' && (
              <div className="card" style={{ marginTop: '1rem', borderLeft: '4px solid var(--accent)' }}>
                <h3 style={{ fontSize: '0.85rem', fontWeight: 700, marginBottom: '0.6rem' }}>
                  💡 自测一下
                </h3>
                <p style={{ fontSize: '0.82rem', marginBottom: '0.6rem' }}>
                  如果先执行 R 再执行 F，对应的矩阵乘积是：
                </p>
                <QuizOptions
                  options={[
                    { label: 'A. R × F', correct: true },
                    { label: 'B. F × R', correct: false },
                    { label: 'C. R + F', correct: false },
                    { label: 'D. R × F = F × R', correct: false },
                  ]}
                  explanation="先 R 后 F = R × F。矩阵乘法不满足交换律，R × F ≠ F × R。操作顺序决定矩阵乘积的顺序。"
                />
              </div>
            )}

            {/* 第4章专属：自测题 */}
            {id === 'inverse' && (
              <div className="card" style={{ marginTop: '1rem', borderLeft: '4px solid var(--accent)' }}>
                <h3 style={{ fontSize: '0.85rem', fontWeight: 700, marginBottom: '0.6rem' }}>
                  💡 自测一下
                </h3>
                <p style={{ fontSize: '0.82rem', marginBottom: '0.6rem' }}>
                  已知操作序列为 R → U → F，正确的逆序撤销序列是：
                </p>
                <QuizOptions
                  options={[
                    { label: "A. R' → U' → F'", correct: false },
                    { label: "B. F' → U' → R'", correct: true },
                    { label: 'C. R → U → F', correct: false },
                    { label: 'D. F → U → R', correct: false },
                  ]}
                  explanation="逆序法则：(R·U·F)⁻¹ = F⁻¹·U⁻¹·R⁻¹。后做的先撤销——最后一步F最先撤销，第一步R最后撤销。就像先穿鞋后穿袜，脱的时候先脱鞋再脱袜。"
                />
              </div>
            )}
          </div>

          {/* ===== 右侧：数学演示 + 操作区 ===== */}
            <div>
              {/* ---- 第3章专属：双魔方并排对比 ---- */}
              {id === 'compose' ? (
                <>
                  {/* 记法说明条 */}
                  <div style={{
                    fontSize: '0.73rem', color: 'var(--ink2)',
                    marginBottom: '0.5rem',
                    display: 'flex', gap: '0.8rem', justifyContent: 'center',
                    background: 'var(--bg2)', borderRadius: '6px',
                    padding: '0.3rem 0.6rem',
                  }}>
                    <span>🟥 <strong>R</strong>=右面</span>
                    <span>🟩 <strong>U</strong>=上面</span>
                    <span>🟦 <strong>F</strong>=前面</span>
                    <span style={{color:'var(--muted)'}}>|</span>
                    <span>带 <strong>'</strong> = 逆时针</span>
                  </div>
                  <div style={{
                  display: 'flex', gap: '0.6rem',
                  marginBottom: '0.6rem',
                }}>
                  {/* 左侧魔方：先①后② */}
                  <div style={{
                    flex: 1, textAlign: 'center',
                    border: '1px solid var(--rule)', borderRadius: 'var(--radius)',
                    overflow: 'hidden',
                  }}>
                    <div style={{
                      height: '22px', lineHeight: '22px',
                      fontSize: '11px', fontWeight: 700,
                      color: '#fff', background: 'var(--accent)',
                    }}>
                      先①后②
                    </div>
                    <div style={{ height: '240px' }}>
                      <Cube3DView ref={leftCubeRef} disableStore />
                    </div>
                  </div>
                  {/* 右侧魔方：先②后① */}
                  <div style={{
                    flex: 1, textAlign: 'center',
                    border: '1px solid var(--rule)', borderRadius: 'var(--radius)',
                    overflow: 'hidden',
                  }}>
                    <div style={{
                      height: '22px', lineHeight: '22px',
                      fontSize: '11px', fontWeight: 700,
                      color: '#fff', background: 'var(--orange)',
                    }}>
                      先②后①
                    </div>
                    <div style={{ height: '240px' }}>
                      <Cube3DView ref={rightCubeRef} disableStore />
                    </div>
                  </div>
                </div>
                </>
              ) : (
                /* ---- 非第3章：单个3D魔方 ---- */
                <>
                {/* 第6节专属：魔方+演示并排 */}
                {id === 'solve' ? (
                  <>
                    {/* 记法说明条 */}
                    <div style={{
                      fontSize: '0.73rem', color: 'var(--ink2)',
                      marginBottom: '0.5rem',
                      display: 'flex', gap: '0.8rem', justifyContent: 'center',
                      background: 'var(--bg2)', borderRadius: '6px',
                      padding: '0.3rem 0.6rem',
                    }}>
                      <span>🟥 <strong>R</strong>=右面</span>
                      <span>🟩 <strong>U</strong>=上面</span>
                      <span>🟦 <strong>F</strong>=前面</span>
                      <span style={{color:'var(--muted)'}}>|</span>
                      <span>带 <strong>'</strong> = 逆时针</span>
                    </div>
                    {/* 3D魔方 */}
                    <div style={{
                      height: '320px', marginBottom: '0.8rem',
                      borderRadius: 'var(--radius)',
                      overflow: 'hidden', border: '1px solid var(--rule)',
                    }}>
                      <Cube3DView key={id} ref={cubeRef} />
                    </div>
                    {/* Tab 演示面板 */}
                    <SolveDemoPanel cubeRef={cubeRef} />
                  </>
                ) : (
                  <>
                  {/* 记法说明条 */}
                  {['intro', 'matrix', 'inverse', 'invariant'].includes(id!) && (
                    <div style={{
                      fontSize: '0.73rem', color: 'var(--ink2)',
                      marginBottom: '0.5rem',
                      display: 'flex', gap: '0.8rem', justifyContent: 'center',
                      background: 'var(--bg2)', borderRadius: '6px',
                      padding: '0.3rem 0.6rem',
                    }}>
                      <span>🟥 <strong>R</strong>=右面</span>
                      <span>🟩 <strong>U</strong>=上面</span>
                      <span>🟦 <strong>F</strong>=前面</span>
                      <span style={{color:'var(--muted)'}}>|</span>
                      <span>带 <strong>\'</strong> = 逆时针</span>
                    </div>
                  )}
                  <div style={{
                    height: '420px', marginBottom: '0.6rem',
                    borderRadius: 'var(--radius)',
                    overflow: 'hidden',
                    border: '1px solid var(--rule)',
                  }}>
                    <Cube3DView key={id} ref={cubeRef} />
                  </div>
                  </>
                )}
                </>
              )}

              {/* ---- 第3章专属：验证区（矩阵已搬至左侧，此处只留联动魔方的验证区） ---- */}
              {id === 'compose' && <ComposeVerify leftCubeRef={leftCubeRef} rightCubeRef={rightCubeRef} />}
              {id === 'compose' && (
                <div style={{ marginTop: '0.8rem', padding: '0.6rem 0.8rem', borderRadius: '6px', background: '#EFF6FF', borderLeft: '3px solid #3B82F6', fontSize: '0.8rem', color: 'var(--ink2)' }}>
                  <strong>因果说明：</strong>R 和 U 操作的顺序之所以影响结果，是因为旋转矩阵乘法不满足交换律。这在数学上等价于：两个旋转的合成结果取决于执行顺序——先绕 X 轴再绕 Y 轴，与先绕 Y 轴再绕 X 轴，得到不同的最终朝向。
                </div>
              )}

              {/* ---- 第4章专属：撤销演示（逆矩阵卡片已搬至左侧） ---- */}
              {id === 'inverse' && <InverseDemo cubeRef={cubeRef} />}

              {/* ---- 第5章专属：不变量观察器 ---- */}
              {id === 'invariant' && <InvariantDemo cubeRef={cubeRef} />}

              {/* 操作提示 */}
              <div style={{ fontSize: '0.8rem', color: 'var(--ink2)', marginBottom: '0.4rem', lineHeight: 1.5 }}>
                {ch.demoHint}
              </div>

              {/* 跳转链接 */}
              <div style={{ textAlign: 'right' }}>
                <Link to={id === 'solve' ? '/tutorial' : '/playground'} state={id === 'solve' ? undefined : {}} style={{ fontSize: '0.82rem', color: 'var(--accent)', textDecoration: 'underline' }}>
                  {id === 'solve' ? '🎯 开始引导：复原第一个角块 →' : '打开实操训练（含计时/撤销）→'}
                </Link>
              </div>
            </div>
          </div>

          {/* 小结条 */}
          {CHAPTER_SUMMARY[id!] && (
            <div style={{ display:'flex', alignItems:'center', gap:'0.6rem', padding:'0.6rem 1rem', marginBottom:'1rem', background:'var(--bg2)', borderRadius:'8px', borderLeft: `4px solid ${CHAPTER_COLORS[id!]}` }}>
              <span style={{ fontSize:'0.75rem', fontWeight:700, color:'var(--muted)' }}>本节要点</span>
              {CHAPTER_SUMMARY[id!].map((point, i) => <span key={i} style={{ fontSize:'0.78rem', color:'var(--ink2)', padding:'0.15rem 0.5rem', borderRadius:'4px', background:'#fff' }}>{point}</span>)}
            </div>
          )}

          {/* 章节导航 */}
          <div className="chapter-nav">
            {ch.prev ? (
              <Link to={`/chapter/${ch.prev}`} className="btn btn-outline">
                ← 上一节：{CHAPTER_CONTENT[ch.prev].title.split('=')[0].trim()}
              </Link>
            ) : <span />}
            {ch.next ? (
              <Link to={`/chapter/${ch.next}`} className="btn btn-primary">
                下一节：{CHAPTER_CONTENT[ch.next].title.split('=')[0].trim()} →
              </Link>
            ) : (
              <Link to="/playground" state={{ fromChapter: 'solve' }} className="btn btn-primary">去实操训练 →</Link>
            )}
          </div>
        </div>
      </div>
    </>
  )
}
