/* Generated by Trae Work */
import { Link } from 'react-router-dom'
import { useRef, useEffect, useState } from 'react'
import Cube3DView from '../components/cube3d/Cube3DView'
import type { Cube3DViewHandle } from '../components/cube3d/Cube3DView'

/** 打乱序列（6步） */
const SCRAMBLE_MOVES = ['R', 'U', "F'", "R'", "U'", 'F']

/** 还原序列（逆序） */
const SOLVE_MOVES = ["F'", 'U', 'R', 'F', "U'", "R'"]

/** 还原步骤的数学标注 */
const solveLabels: Record<number, { text: string; color: string }> = {
  0: { text: "F' = 绕Z轴 -90° → 逆旋转矩阵", color: '#10B981' },
  1: { text: 'U = 绕Y轴 +90° → 旋转矩阵', color: '#10B981' },
  2: { text: 'R = 绕X轴 +90° → 旋转矩阵', color: '#10B981' },
  3: { text: 'F = 绕Z轴 +90° → 旋转矩阵', color: '#10B981' },
  4: { text: "U' = 绕Y轴 -90° → 逆旋转矩阵", color: '#10B981' },
  5: { text: "R' = (R·U·F)⁻¹ = F⁻¹·U⁻¹·R⁻¹ → 逆序列法则", color: '#EF4444' },
}

/** 首页 — 参赛项目介绍页 */
export default function Landing() {
  const cubeRef = useRef<Cube3DViewHandle>(null)
  const [stepIndex, setStepIndex] = useState(-1)

  /* 自动播放循环：打乱 → 还原 */
  useEffect(() => {
    const allMoves = [...SCRAMBLE_MOVES, ...SOLVE_MOVES]
    let i = 0
    const timer = setInterval(() => {
      if (cubeRef.current && i < allMoves.length) {
        cubeRef.current.executeMove(allMoves[i])
        setStepIndex(i)
        i++
      } else {
        cubeRef.current?.reset()
        setStepIndex(-1)
        i = 0
      }
    }, 800)
    return () => clearInterval(timer)
  }, [])

  return (
    <>
      {/* ===== Hero（左右双栏） ===== */}
      <div className="hero">
        <div className="hero-inner">
          {/* 左：文字区 */}
          <div className="hero-text">
            <div className="hero-badge">线性代数 × 魔方</div>
            <h1>魔方不是靠背的<br />是用<em>数学</em>推出来的</h1>
            <p className="sub">
              用线性代数思维理解魔方转动，用抵消法自主推导复原方案——零公式，纯逻辑。
            </p>
            <p style={{
              fontSize: '0.88rem', fontWeight: 700, color: 'var(--accent)',
              marginTop: '-0.5rem', marginBottom: '1.5rem',
            }}>
              每一步转动都有数学解释 — 用线性代数 0 公式还原魔方
            </p>
            <div className="btn-row">
              <Link to="/chapter/intro" className="btn btn-primary">从零开始，用数学看懂魔方</Link>
              <Link to="/chapter/solve" className="btn btn-outline">动手推导，体验复原逻辑</Link>
            </div>
          </div>

          {/* 右：3D 魔方 + 公式标注 */}
          <div className="hero-visual">
            <div style={{
              width: '340px', height: '340px',
              borderRadius: 'var(--radius)',
              overflow: 'hidden', border: '1px solid var(--rule)',
            }}>
              <Cube3DView ref={cubeRef} disableStore />
            </div>
            <div style={{ marginTop: '0.6rem', minHeight: '2rem' }}>
              {stepIndex >= 0 && (
                <div style={{
                  padding: '0.4rem 0.8rem', borderRadius: '8px',
                  background: stepIndex < SCRAMBLE_MOVES.length ? '#EFF6FF' : '#FEF3C7',
                  fontSize: '0.78rem', fontWeight: 600,
                  borderLeft: `3px solid ${
                    stepIndex < SCRAMBLE_MOVES.length ? '#3B82F6' : '#F59E0B'
                  }`,
                  transition: 'all 0.3s ease',
                }}>
                  {stepIndex < SCRAMBLE_MOVES.length
                    ? `打乱中… ${SCRAMBLE_MOVES[stepIndex]}`
                    : solveLabels[stepIndex - SCRAMBLE_MOVES.length]?.text ?? '…'}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* ===== 快速体验入口 ===== */}
      <div className="section-sm" style={{ textAlign: 'center' }}>
        <div className="container">
          <Link
            to="/chapter/compose"
            style={{
              display: 'inline-flex', alignItems: 'center', gap: '0.5rem',
              padding: '0.9rem 2rem',
              background: 'linear-gradient(135deg, var(--accent), var(--accent-d))',
              color: '#fff', fontWeight: 700, fontSize: '1.05rem',
              borderRadius: '14px', textDecoration: 'none',
              boxShadow: '0 4px 24px rgba(37,99,235,0.35)',
              transition: 'transform 0.2s, box-shadow 0.2s',
            }}
            onMouseEnter={(e) => { (e.currentTarget as HTMLAnchorElement).style.transform = 'translateY(-2px)'; (e.currentTarget as HTMLAnchorElement).style.boxShadow = '0 6px 32px rgba(37,99,235,0.45)' }}
            onMouseLeave={(e) => { (e.currentTarget as HTMLAnchorElement).style.transform = ''; (e.currentTarget as HTMLAnchorElement).style.boxShadow = '0 4px 24px rgba(37,99,235,0.35)' }}
          >
            直接上手体验 →
          </Link>
          <p style={{
            color: 'var(--ink2)', fontSize: '0.82rem',
            marginTop: '0.6rem',
          }}>
            先看看矩阵乘法为什么不能交换 —— 3 分钟理解线代和魔方的关联
          </p>
        </div>
      </div>

      {/* ===== 亮点卡片（3个） ===== */}
      <div className="section-sm">
        <div className="container">
          <div className="card-grid">
            <div className="card">
              <span className="card-icon">🧩</span>
              <h3>零公式复原</h3>
              <p>不靠死记硬背，用逆变换逻辑自主推导每一步操作</p>
            </div>
            <div className="card">
              <span className="card-icon">🖐️</span>
              <h3>交互式学习</h3>
              <p>所有概念均可动手操作，拖动魔方直接感受变换效果</p>
            </div>
            <div className="card">
              <span className="card-icon">📐</span>
              <h3>线代思维复用</h3>
              <p>把课本知识落地，真正理解矩阵、逆矩阵、交换律</p>
            </div>
          </div>
        </div>
      </div>

      {/* ===== 后续路线图 ===== */}
      <div className="section">
        <div className="container">
          <h2 style={{
            textAlign: 'center', fontSize: '1.3rem', fontWeight: 700,
            marginBottom: '1.8rem',
          }}>
            后续演进路线
          </h2>
          {/* 时间线 */}
          <div style={{
            maxWidth: '600px', margin: '0 auto',
            borderLeft: '3px solid var(--accent)',
            paddingLeft: '1.5rem',
          }}>
            {[
              { stage: '阶段一（当前 Demo）', desc: '三阶魔方 + 线代概念科普 + 引导复原演示（底面十字→角块→中层→顶面十字）' },
              { stage: '阶段二', desc: '引入二阶魔方，30 分钟零基础入门（仅需一个公式 R U R\' U\'）' },
              { stage: '阶段三', desc: '三阶完整复原教学（七步引导，每步对应线代概念，含分步检测与提示系统）' },
              { stage: '阶段四', desc: '从线代类比走向群论入门，完成"类比→严谨"的学术过渡' },
            ].map((item, i) => (
              <div key={i} style={{
                position: 'relative', marginBottom: i < 3 ? '1.5rem' : 0,
                paddingBottom: i < 3 ? '1.5rem' : 0,
              }}>
                {/* 时间线圆点 */}
                <div style={{
                  position: 'absolute', left: '-1.8rem', top: '0.3rem',
                  width: '14px', height: '14px', borderRadius: '50%',
                  background: i === 0 ? 'var(--accent)' : 'var(--rule)',
                  border: i === 0 ? '3px solid var(--accent)' : '3px solid var(--rule)',
                }} />
                <div style={{
                  fontWeight: 700, fontSize: '0.9rem',
                  color: i === 0 ? 'var(--accent)' : 'var(--ink)',
                  marginBottom: '0.2rem',
                }}>
                  {item.stage}
                </div>
                <div style={{ fontSize: '0.84rem', color: 'var(--ink2)' }}>
                  {item.desc}
                </div>
                {/* 向下箭头 */}
                {i < 3 && (
                  <div style={{
                    marginTop: '0.6rem', marginLeft: '-0.2rem',
                    fontSize: '0.8rem', color: 'var(--muted)',
                  }}>
                    ↓
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ===== 免责声明 ===== */}
      <div className="section-sm">
        <div className="container">
          <div className="notice">
            📐 <strong>类比说明</strong>：本站用线性代数做类比科普，帮助理解魔方变换的行为逻辑。
            魔方的严谨数学本质是<strong>置换群（鲁比克群）</strong>。想了解严谨数学？
            <Link to="/archive"> 前往数学档案馆 →</Link>
          </div>
        </div>
      </div>
    </>
  )
}
