/* Generated by Trae Work */
import { Link } from 'react-router-dom'

/** 首页 — 参赛项目介绍页 */
export default function Landing() {
  return (
    <>
      {/* ===== Hero ===== */}
      <div className="hero">
        <div className="hero-badge">线性代数 × 魔方</div>
        <h1>魔方不是靠背的<br />是用<em>数学</em>推出来的</h1>
        <p className="sub">
          用线性代数思维理解魔方转动，用抵消法自主推导复原方案——零公式，纯逻辑。
        </p>
        <div className="btn-row">
          <Link to="/chapter/intro" className="btn btn-primary">📖 从零开始，用数学看懂魔方</Link>
          <Link to="/chapter/solve" className="btn btn-outline">🧊 动手推导，体验复原逻辑</Link>
        </div>
      </div>

      {/* ===== 快速体验入口 ===== */}
      <div className="section-sm" style={{ textAlign: 'center' }}>
        <div className="container">
          <Link
            to="/chapter/compose"
            style={{
              display: 'inline-flex', alignItems: 'center', gap: '0.5rem',
              padding: '0.9rem 2rem',
              background: 'linear-gradient(135deg, var(--accent), var(--accent-d))',
              color: '#fff', fontWeight: 700, fontSize: '1.05rem',
              borderRadius: '14px', textDecoration: 'none',
              boxShadow: '0 4px 24px rgba(37,99,235,0.35)',
              transition: 'transform 0.2s, box-shadow 0.2s',
            }}
            onMouseEnter={(e) => { (e.currentTarget as HTMLAnchorElement).style.transform = 'translateY(-2px)'; (e.currentTarget as HTMLAnchorElement).style.boxShadow = '0 6px 32px rgba(37,99,235,0.45)' }}
            onMouseLeave={(e) => { (e.currentTarget as HTMLAnchorElement).style.transform = ''; (e.currentTarget as HTMLAnchorElement).style.boxShadow = '0 4px 24px rgba(37,99,235,0.35)' }}
          >
            🎮 直接上手体验 →
          </Link>
          <p style={{
            color: 'var(--ink2)', fontSize: '0.82rem',
            marginTop: '0.6rem',
          }}>
            先看看矩阵乘法为什么不能交换 —— 3 分钟理解线代和魔方的关联
          </p>
        </div>
      </div>

      {/* ===== 亮点卡片（3个） ===== */}
      <div className="section-sm">
        <div className="container">
          <div className="card-grid">
            <div className="card">
              <span className="card-icon">🧩</span>
              <h3>零公式复原</h3>
              <p>不靠死记硬背，用逆变换逻辑自主推导每一步操作</p>
            </div>
            <div className="card">
              <span className="card-icon">🖐️</span>
              <h3>交互式学习</h3>
              <p>所有概念均可动手操作，拖动魔方直接感受变换效果</p>
            </div>
            <div className="card">
              <span className="card-icon">📐</span>
              <h3>线代思维复用</h3>
              <p>把课本知识落地，真正理解矩阵、逆矩阵、交换律</p>
            </div>
          </div>
        </div>
      </div>

      {/* ===== 后续路线图 ===== */}
      <div className="section">
        <div className="container">
          <h2 style={{
            textAlign: 'center', fontSize: '1.3rem', fontWeight: 700,
            marginBottom: '1.8rem',
          }}>
            🧭 后续演进路线
          </h2>
          {/* 时间线 */}
          <div style={{
            maxWidth: '600px', margin: '0 auto',
            borderLeft: '3px solid var(--accent)',
            paddingLeft: '1.5rem',
          }}>
            {[
              { stage: '阶段一（当前 Demo）', desc: '三阶魔方 + 线代概念科普 + 角块引导复原演示' },
              { stage: '阶段二', desc: `引入二阶魔方，30 分钟零基础入门（仅需一个公式 R U R' U'）` },
              { stage: '阶段三', desc: '三阶完整复原教学（七步引导，每步对应线代概念，含分步检测与提示系统）' },
              { stage: '阶段四', desc: '从线代类比走向群论入门，完成"类比→严谨"的学术过渡' },
            ].map((item, i) => (
              <div key={i} style={{
                position: 'relative', marginBottom: i < 3 ? '1.5rem' : 0,
                paddingBottom: i < 3 ? '1.5rem' : 0,
              }}>
                {/* 时间线圆点 */}
                <div style={{
                  position: 'absolute', left: '-1.8rem', top: '0.3rem',
                  width: '14px', height: '14px', borderRadius: '50%',
                  background: i === 0 ? 'var(--accent)' : 'var(--rule)',
                  border: i === 0 ? '3px solid var(--accent)' : '3px solid var(--rule)',
                }} />
                <div style={{
                  fontWeight: 700, fontSize: '0.9rem',
                  color: i === 0 ? 'var(--accent)' : 'var(--ink)',
                  marginBottom: '0.2rem',
                }}>
                  {item.stage}
                </div>
                <div style={{ fontSize: '0.84rem', color: 'var(--ink2)' }}>
                  {item.desc}
                </div>
                {/* 向下箭头 */}
                {i < 3 && (
                  <div style={{
                    marginTop: '0.6rem', marginLeft: '-0.2rem',
                    fontSize: '0.8rem', color: 'var(--muted)',
                  }}>
                    ↓
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ===== 免责声明 ===== */}
      <div className="section-sm">
        <div className="container">
          <div className="notice">
            📐 <strong>类比说明</strong>：本站用线性代数做类比科普，帮助理解魔方变换的行为逻辑。
            魔方的严谨数学本质是<strong>置换群（鲁比克群）</strong>。想了解严谨数学？
            <Link to="/archive"> 前往数学档案馆 →</Link>
          </div>
        </div>
      </div>
    </>
  )
}
