/* Generated by Trae Work */
import { useState, useRef, useCallback, useEffect } from 'react'
import { Link, useLocation } from 'react-router-dom'
import Cube3DView from '../components/cube3d/Cube3DView'
import type { Cube3DViewHandle } from '../components/cube3d/Cube3DView'
import { useCubeStore } from '../store/cubeStore'
import { createSolvedCube, isSolved as checkIsSolved } from '../lib/cubeLogic'

/** 练习模式类型 */
type PlayMode = 'teach' | 'practice' | 'challenge'

/** 模式配置 */
const MODE_CONFIG: Record<PlayMode, { label: string; desc: string }> = {
  teach:     { label: '教学模式', desc: '每步操作实时显示对应旋转矩阵，帮助理解"转动=矩阵变换"' },
  practice:  { label: '练习模式', desc: '记录操作历史并提供提示，适合独立尝试复原' },
  challenge: { label: '挑战模式', desc: '隐藏一切提示和历史，纯靠记忆和推理复原' },
}

/** 实操训练页面 — 3D魔方 + 操作面板 */
export default function Playground() {
  /* ---- 引用 ---- */
  const cubeRef = useRef<Cube3DViewHandle>(null)

  /* ---- Zustand store ---- */
  const moveHistory = useCubeStore((s) => s.history)
  /** 路由来源信息 */
  const location = useLocation()
  const fromChapter = (location.state as any)?.fromChapter as string | undefined

  /* ---- 本地状态 ---- */
  const [mode, setMode] = useState<PlayMode>('teach')
  /** 计时器状态 */
  const [timer, setTimer] = useState(0)
  const [timerRunning, setTimerRunning] = useState(false)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  /** 还原成功弹窗 */
  const [showSolved, setShowSolved] = useState(false)
  /** 是否来自打乱（防止初始状态弹窗） */
  const [wasScrambled, setWasScrambled] = useState(false)
  /** 上一次操作步数（用于检测"刚刚又操作了一步"） */
  const lastHistoryLen = useRef(0)
  /** 新手引导提示是否显示（首次进入时显示） */
  const [showGuide, setShowGuide] = useState(true)
  /** 练习模式提示文本 */
  const [hint, setHint] = useState<string | null>(null)

  /* ---- 计时器逻辑 ---- */
  const hasStarted = useRef(false)  // 是否已经开始过（用于区分首次开始和继续计时）

  const startTimer = useCallback(() => {
    if (timerRunning) return
    setTimerRunning(true)
    if (!hasStarted.current) {
      // 首次开始时归零
      setTimer(0)
      hasStarted.current = true
    }
    // 暂停后继续时不归零，直接接着计
    timerRef.current = setInterval(() => {
      setTimer((t) => t + 1)
    }, 1000)
  }, [timerRunning])

  const stopTimer = useCallback(() => {
    setTimerRunning(false)
    if (timerRef.current) { clearInterval(timerRef.current); timerRef.current = null }
  }, [])

  /* ---- 操作按钮处理 ---- */
  /** 打乱魔方 */
  const handleScramble = () => {
    cubeRef.current?.scramble(20)
    setWasScrambled(true)
    setShowSolved(false)
    hasStarted.current = false
    startTimer()
  }

  /** 重置魔方 */
  const handleReset = () => {
    cubeRef.current?.reset()
    setWasScrambled(false)
    setShowSolved(false)
    stopTimer()
    setTimer(0)
    hasStarted.current = false
  }

  /** Move 对象 → 标准旋转变换记法（如 "R"、"U'"） */
  const moveToNotation = (move: { axis: string; layer: number; direction: number }): string => {
    const faceMap: Record<string, Record<number, string>> = {
      x: { 1: 'R', [-1]: 'L' },
      y: { 1: 'U', [-1]: 'D' },
      z: { 1: 'F', [-1]: 'B' },
    }
    const face = faceMap[move.axis]?.[move.layer] ?? move.axis
    return move.direction === 1 ? face : face + "'"
  }

  /** 撤销上一步：执行最后一步的逆操作 */
  const handleUndo = () => {
    const store = useCubeStore.getState()
    if (store.history.length === 0) return

    const lastMove = store.history[store.history.length - 1]
    const reverseNotation = moveToNotation({ ...lastMove, direction: (lastMove.direction * -1) as 1 | -1 })

    // 3D 魔方执行逆操作动画（不写 store）
    cubeRef.current?.undoMove(reverseNotation)

    // store 移除最后一条记录
    store.undo()
  }

  /** 练习模式提示：基于打乱历史反推下一步建议 */
  const handleHint = () => {
    const store = useCubeStore.getState()
    if (store.history.length === 0) {
      setHint('魔方已是还原状态，试试先点击"打乱"按钮。')
      return
    }
    // 提示最后一步的逆操作（最简单的还原思路：后做的先撤销）
    const lastMove = store.history[store.history.length - 1]
    const reverseMove = { ...lastMove, direction: (lastMove.direction * -1) as 1 | -1 }
    const reverseNotation = moveToNotation(reverseMove)
    setHint(`提示：试试执行 ${reverseNotation}（撤销最后一步操作）。核心思路——后做的先撤销。`)
  }

  /** 格式化时间 */
  const formatTime = (seconds: number) => {
    const m = Math.floor(seconds / 60)
    const s = seconds % 60
    return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
  }

  /* ---- 还原检测：监听操作历史变化 ---- */
  useEffect(() => {
    if (!wasScrambled) return // 初始归零才算还原
    if (moveHistory.length === 0) return // 重置时已处理

    // 只有在刚刚多了一步操作时才检测
    if (moveHistory.length <= lastHistoryLen.current) {
      lastHistoryLen.current = moveHistory.length
      return
    }
    lastHistoryLen.current = moveHistory.length

    // 从 store 获取当前 cubie 数据并检测
    const { cubies } = useCubeStore.getState()
    const solvedCubies = createSolvedCube()
    if (checkIsSolved(cubies)) {
      setShowSolved(true)
      stopTimer()
    }
  }, [moveHistory, wasScrambled, stopTimer])

  /** 魔方操作历史显示文本 */
  const historyText = moveHistory.map((m) => {
    const faceNames: Record<string, string> = { x: 'R', y: 'U', z: 'F' }
    const dirText = m.direction === 1 ? '' : "'"
    return `${faceNames[m.axis] || m.axis}${dirText}`
  }).join(' → ')

  return (
    <>
      {/* ===== 主内容 ===== */}
      {/* 来源提示 */}
      {fromChapter && (
        <div style={{
          maxWidth: '860px', margin: '0 auto 1rem',
          padding: '0.6rem 1rem', borderRadius: '8px',
          background: '#FEF9C3', border: '1px solid #FDE047',
          fontSize: '0.8rem',
        }}>
          📖 你从<span style={{ fontWeight: 700 }}>第{fromChapter === 'solve' ? '6' : fromChapter}节</span>跳转过来，建议先把上方第二章～第五章过一遍：
          {fromChapter === 'solve' ? ' 逆矩阵+抵消法 → ' : ' '}
          <Link to="/chapter/compose" style={{ fontWeight: 600, textDecoration: 'underline', color: 'var(--accent)' }}>
            第3章：矩阵乘法/交换律
          </Link>
          {' | '}
          <Link to="/chapter/inverse" style={{ fontWeight: 600, textDecoration: 'underline', color: 'var(--accent)' }}>
            第4章：逆矩阵/逆序法则
          </Link>
        </div>
      )}
      <div className="section">
        <div className="container">
          <h2 style={{ fontSize: '1.5rem', fontWeight: 700, marginBottom: '1rem' }}>
            虚拟魔方实操厅
          </h2>

          {/* 模式切换 */}
          <div style={{
            display: 'flex', gap: '0.4rem', marginBottom: '0.8rem',
            flexWrap: 'wrap',
          }}>
            {(Object.keys(MODE_CONFIG) as PlayMode[]).map((key) => (
              <button
                key={key}
                className={mode === key ? 'btn btn-primary' : 'btn btn-outline'}
                style={{ fontSize: '0.8rem', padding: '0.4rem 0.8rem' }}
                onClick={() => setMode(key)}
              >
                {MODE_CONFIG[key].label}
              </button>
            ))}
          </div>
          {/* 模式说明 */}
          <p style={{
            fontSize: '0.82rem', color: 'var(--ink2)',
            marginBottom: '1.2rem',
          }}>
            {MODE_CONFIG[mode].desc}
          </p>

          {/* 新手引导横幅（首次进入显示，可关闭） */}
          {showGuide && (
            <div style={{
              display: 'flex', alignItems: 'flex-start', gap: '0.6rem',
              padding: '0.7rem 1rem', marginBottom: '1rem',
              background: 'linear-gradient(135deg, #EFF6FF, #DBEAFE)',
              borderRadius: '8px', border: '1px solid #BFDBFE',
            }}>
              <span style={{ fontSize: '1.1rem' }}>👋</span>
              <div style={{ flex: 1, fontSize: '0.8rem', color: 'var(--ink2)' }}>
                <strong>欢迎来到实操厅！</strong>
                <div style={{ marginTop: '0.3rem' }}>
                  ① 点击「打乱」按钮随机打乱魔方 →
                  ② 用<strong>左键</strong>点击魔方面 = 逆时针，<strong>右键</strong> = 顺时针 →
                  ③ 目标：让每面恢复同色。可随时「撤销」或「重置」。
                </div>
              </div>
              <button
                onClick={() => setShowGuide(false)}
                style={{
                  background: 'none', border: 'none', cursor: 'pointer',
                  fontSize: '1rem', color: 'var(--muted)', padding: '0',
                }}
              >
                ✕
              </button>
            </div>
          )}

          {/* 双栏布局 */}
          <div className="two-col">
            {/* 左侧：3D 魔方 */}
            <div style={{ minHeight: '460px', display: 'flex', flexDirection: 'column' }}>
              <Cube3DView ref={cubeRef} />
            </div>

            {/* 右侧：控制面板 */}
            <div>
              {/* 操作按钮行 */}
              <div style={{
                display: 'flex', gap: '0.4rem', marginBottom: '1rem',
                flexWrap: 'wrap',
              }}>
                <button
                  className="btn btn-outline"
                  style={{ fontSize: '0.82rem', padding: '0.45rem 0.9rem' }}
                  onClick={handleScramble}
                >
                  打乱
                </button>
                <button
                  className="btn btn-outline"
                  style={{ fontSize: '0.82rem', padding: '0.45rem 0.9rem' }}
                  onClick={handleReset}
                >
                  重置
                </button>
                <button
                  className="btn btn-outline"
                  style={{
                    fontSize: '0.82rem', padding: '0.45rem 0.9rem',
                    opacity: moveHistory.length === 0 ? 0.4 : 1,
                  }}
                  onClick={handleUndo}
                  disabled={moveHistory.length === 0}
                >
                  撤销
                </button>
                <button
                  className="btn btn-outline"
                  style={{ fontSize: '0.82rem', padding: '0.45rem 0.9rem' }}
                  onClick={timerRunning ? stopTimer : startTimer}
                >
                  {timerRunning ? formatTime(timer) : '计时'} {timerRunning ? '||' : ''}
                </button>
                {/* 练习模式专属：提示按钮 */}
                {mode === 'practice' && (
                  <button
                    className="btn btn-outline"
                    style={{ fontSize: '0.82rem', padding: '0.45rem 0.9rem' }}
                    onClick={handleHint}
                  >
                    💡 提示
                  </button>
                )}
              </div>

              {/* 练习模式提示文本 */}
              {hint && (
                <div style={{
                  padding: '0.5rem 0.8rem', marginBottom: '0.8rem',
                  background: '#FEF3C7', borderRadius: '6px',
                  fontSize: '0.8rem', color: 'var(--ink2)',
                  borderLeft: '3px solid #F59E0B',
                }}>
                  {hint}
                </div>
              )}

              {/* 操作历史（挑战模式下隐藏） */}
              {mode !== 'challenge' && (
              <div className="card" style={{ marginBottom: '1rem' }}>
                <h3 style={{ fontSize: '0.85rem', marginBottom: '0.5rem' }}>
                  操作历史 ({moveHistory.length} 步)
                </h3>
                {moveHistory.length === 0 ? (
                  <p style={{ fontSize: '0.8rem', color: 'var(--muted)' }}>
                    左键点击面 = 逆时针，右键点击面 = 顺时针，或点击"打乱"
                  </p>
                ) : (
                  <div style={{
                    fontFamily: 'monospace', fontSize: '0.78rem',
                    color: 'var(--accent)', maxHeight: '150px',
                    overflow: 'auto', lineHeight: 1.6,
                    wordBreak: 'break-all',
                  }}>
                    {historyText}
                  </div>
                )}
              </div>
              )}

              {/* 教学模式：显示最近操作的旋转矩阵 */}
              {mode === 'teach' && moveHistory.length > 0 && (
                <div className="card" style={{ marginBottom: '1rem', borderLeft: '4px solid #8B5CF6' }}>
                  <h3 style={{ fontSize: '0.85rem', marginBottom: '0.5rem' }}>
                    矩阵解读
                  </h3>
                  {(() => {
                    const last = moveHistory[moveHistory.length - 1]
                    const faceMap: Record<string, Record<number, string>> = {
                      x: { 1: 'R', [-1]: 'L' },
                      y: { 1: 'U', [-1]: 'D' },
                      z: { 1: 'F', [-1]: 'B' },
                    }
                    const face = faceMap[last.axis]?.[last.layer] ?? last.axis.toUpperCase()
                    const notation = last.direction === 1 ? face : face + "'"
                    const matrixMap: Record<string, number[][]> = {
                      R: [[1,0,0],[0,0,-1],[0,1,0]], L: [[1,0,0],[0,0,1],[0,-1,0]],
                      U: [[0,0,-1],[0,1,0],[1,0,0]], D: [[0,0,1],[0,1,0],[-1,0,0]],
                      F: [[0,1,0],[1,0,0],[0,0,1]], B: [[0,-1,0],[-1,0,0],[0,0,1]],
                    }
                    const mat = matrixMap[face] || [[1,0,0],[0,1,0],[0,0,1]]
                    const isInverse = notation.includes("'")
                    return (
                      <div>
                        <p style={{ fontSize: '0.8rem', color: 'var(--ink2)', marginBottom: '0.5rem' }}>
                          最后一步 <strong style={{ fontFamily: 'monospace' }}>{notation}</strong>
                          {isInverse ? '（逆时针）= 矩阵的逆' : '（顺时针）'}
                        </p>
                        <div style={{
                          fontFamily: 'monospace', fontSize: '0.75rem',
                          background: '#F5F3FF', padding: '0.5rem 0.8rem',
                          borderRadius: '6px', marginBottom: '0.5rem',
                        }}>
                          <div>[{mat[0].map(v => (isInverse ? v === -1 ? ' 1' : v === 1 ? '-1' : ' 0' : (v < 0 ? ' ' : '  ') + v).padStart(3)).join(',')}]</div>
                          <div>[{mat[1].map(v => (isInverse ? v === -1 ? ' 1' : v === 1 ? '-1' : ' 0' : (v < 0 ? ' ' : '  ') + v).padStart(3)).join(',')}]</div>
                          <div>[{mat[2].map(v => (isInverse ? v === -1 ? ' 1' : v === 1 ? '-1' : ' 0' : (v < 0 ? ' ' : '  ') + v).padStart(3)).join(',')}]</div>
                        </div>
                        <p style={{ fontSize: '0.75rem', color: 'var(--muted)' }}>
                          {isInverse
                            ? '逆时针 = 顺时针矩阵的转置（正交矩阵性质：R⁻¹ = Rᵀ）'
                            : '这个矩阵将方块绕对应轴旋转 90°'}
                        </p>
                      </div>
                    )
                  })()}
                </div>
              )}

              {/* 教学模式提示 */}
              {mode === 'teach' && (
                <div className="analogy-note">
                  <span>教学模式：每步操作都会显示对应的旋转矩阵。配合第2节的内容理解"转动=矩阵变换"。</span>
                </div>
              )}
              {/* 练习模式提示 */}
              {mode === 'practice' && (
                <div className="analogy-note">
                  <span>练习模式：记录你的操作并提供💡提示。尝试独立复原，卡住时再求助。</span>
                </div>
              )}
              {mode === 'challenge' && (
                <div className="analogy-note" style={{ borderLeftColor: 'var(--orange)' }}>
                  <span>挑战模式：不依赖操作历史，尝试凭记忆推导还原步骤</span>
                </div>
              )}
            </div>
          </div>

          {/* 底部提示 */}
          <div style={{
            marginTop: '2rem', padding: '1rem 1.2rem',
            background: 'var(--bg2)', borderRadius: 'var(--radius)',
            fontSize: '0.83rem', color: 'var(--ink2)',
            borderLeft: '3px solid var(--accent)',
          }}>
            <strong>交互说明：</strong>
            鼠标左键点击面 = 逆时针旋转
            &nbsp;|&nbsp;
            鼠标右键点击面 = 顺时针旋转
            &nbsp;|&nbsp;
            空白处拖拽 = 旋转视角
            &nbsp;|&nbsp;
            滚轮 = 缩放
          </div>

          {/* 还原成功弹窗 */}
          {showSolved && (
            <div style={{
              position: 'fixed', inset: 0, zIndex: 1000,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              background: 'rgba(0,0,0,0.45)',
            }}>
              <div style={{
                background: '#fff', borderRadius: '16px', padding: '2rem 2.5rem',
                textAlign: 'center', maxWidth: '380px', width: '90%',
                boxShadow: '0 16px 48px rgba(0,0,0,0.2)',
              }}>
                <div style={{ fontSize: '3rem', marginBottom: '0.5rem' }}>🎉</div>
                <h3 style={{ fontSize: '1.3rem', fontWeight: 700, marginBottom: '0.4rem' }}>
                  还原成功！
                </h3>
                <p style={{ fontSize: '0.9rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  你使用了  {moveHistory.length}  步操作将魔方还原！
                  {moveHistory.length <= 22 && (
                    <span style={{ display: 'block', marginTop: '0.3rem', fontWeight: 600, color: 'var(--accent)' }}>
                      🌟 步数 ≤ 22，非常高效！
                    </span>
                  )}
                  {moveHistory.length > 22 && moveHistory.length <= 30 && (
                    <span style={{ display: 'block', marginTop: '0.3rem', fontWeight: 600, color: 'var(--green)' }}>
                      👍 不错！继续优化步数
                    </span>
                  )}
                </p>
                <p style={{ fontSize: '0.8rem', color: 'var(--muted)', marginBottom: '1.2rem' }}>
                  用时 {formatTime(timer)}
                </p>
                <button
                  className="btn btn-primary"
                  onClick={() => setShowSolved(false)}
                  style={{ width: '100%' }}
                >
                  继续挑战
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  )
}
