/* Generated by Trae Work */
import { useRef, useState, useEffect, useCallback } from 'react'
import { Link } from 'react-router-dom'
import Cube3DView from '../components/cube3d/Cube3DView'
import type { Cube3DViewHandle } from '../components/cube3d/Cube3DView'
import { useCubeStore } from '../store/cubeStore'
import { isSolved } from '../lib/cubeLogic'
import type { Move } from '../types/cube'

/* ==================================================================== */
/*  常量定义                                                               */
/* ==================================================================== */

/** 教程阶段类型 */
type Phase =
  | 'cross'          /* 步骤1：白色十字 — 观察 */
  | 'corner-intro'   /* 步骤2：白色角块 — 介绍 */
  | 'corner-guided'  /* 步骤2：白色角块 — 引导演示 */
  | 'corner-practice'/* 步骤2：白色角块 — 实操 */
  | 'corner-done'    /* 步骤2：完成 */
  | 'edge-intro'     /* 步骤3：中层棱块 — 介绍 */
  | 'edge-guided'    /* 步骤3：中层棱块 — 引导演示 */
  | 'edge-practice'  /* 步骤3：中层棱块 — 实操 */
  | 'done'           /* 全部完成 */

/* ---- 白色角块常量（步骤2） ---- */

/** 初始打乱：D' → R' → D → R — 打乱一个角块 */
const CORNER_INITIAL_MOVES: Move[] = [
  { axis: 'y', layer: -1, direction: -1 }, // D'
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: -1, direction: 1 },  // D
  { axis: 'x', layer: 1, direction: 1 },   // R
]

/** 角块解法：R' → D' → R → D — CORNER_INITIAL_MOVES 的逆操作 */
const CORNER_SOLUTION_MOVES: Move[] = [
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: -1, direction: -1 }, // D'
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: -1, direction: 1 },  // D
]

const CORNER_GUIDED_STEPS = [
  { notation: "R'", text: '打开右面空间，准备接收角块' },
  { notation: "D'", text: '移动底层，将目标位置对准角块' },
  { notation: 'R', text: '角块进入正确位置' },
  { notation: 'D', text: '恢复底层，角块归位完成' },
]

/* ---- 中层棱块常量（步骤3） ---- */

/** 初始打乱：F' → U' → F → U → R → U → R' → U'
 *  这是 EDGE_SOLUTION_MOVES 的逆操作，把一个中层棱块移到顶层 */
const EDGE_INITIAL_MOVES: Move[] = [
  { axis: 'z', layer: 1, direction: -1 },  // F'
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'z', layer: 1, direction: 1 },   // F
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: 1, direction: -1 },  // U'
]

/** 棱块解法：U → R → U' → R' → U' → F' → U → F */
const EDGE_SOLUTION_MOVES: Move[] = [
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'z', layer: 1, direction: -1 },  // F'
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'z', layer: 1, direction: 1 },   // F
]

const EDGE_GUIDED_STEPS = [
  { notation: 'U', text: '将顶层目标棱块移到右前准备位置' },
  { notation: 'R', text: '打开右侧面，为棱块创造中层入口' },
  { notation: "U'", text: '沿顶层将棱块推入右侧开口' },
  { notation: "R'", text: '关闭右侧面，棱块被锁定到中层' },
  { notation: "U'", text: '恢复顶层位置' },
  { notation: "F'", text: '打开前面，为朝向调整做准备' },
  { notation: 'U', text: '调整顶层，棱块朝向修正' },
  { notation: 'F', text: '关闭前面，棱块完全归位' },
]

/* ---- 工具函数 ---- */

/** Move → 记法文本 */
function moveToNotation(m: Move): string {
  const faceMap: Record<string, Record<string, string>> = {
    x: { '1': 'R', '-1': 'L' },
    y: { '1': 'U', '-1': 'D' },
    z: { '1': 'F', '-1': 'B' },
  }
  const face = faceMap[m.axis]?.[String(m.layer)] ?? m.axis.toUpperCase()
  return m.direction === 1 ? face : face + "'"
}

/** 获取当前阶段的元信息 */
function getTaskInfo(phase: Phase): { step: number; total: number; name: string } {
  if (phase === 'cross') return { step: 1, total: 3, name: '白色十字' }
  if (phase.startsWith('corner-')) return { step: 2, total: 3, name: '白色角块' }
  if (phase.startsWith('edge-')) return { step: 3, total: 3, name: '中层棱块' }
  return { step: 3, total: 3, name: '全部完成' }
}

/* ==================================================================== */
/*  组件                                                                  */
/* ==================================================================== */

export default function Tutorial() {
  /* ---- 引用 ---- */
  const cubeRef = useRef<Cube3DViewHandle>(null)

  /* ---- 本地状态 ---- */
  const [phase, setPhase] = useState<Phase>('cross')
  const [guidedIdx, setGuidedIdx] = useState(-1)
  const [initialized, setInitialized] = useState(false)
  const [done, setDone] = useState(false)          // 当前任务是否完成
  const [starVisible, setStarVisible] = useState(false)
  const [userNotations, setUserNotations] = useState<string[]>([])
  const [ready, setReady] = useState(false)        // 初始动画播放完毕，可以开始操作
  const [retryKey, setRetryKey] = useState(0)        // 用于强制重新触发 reset 操作

  /* ---- Zustand store ---- */
  const storeHistory = useCubeStore((s) => s.history)
  const storeCubies = useCubeStore((s) => s.cubies)
  const storeReset = useCubeStore((s) => s.reset)

  /* ===== 初始化：cross 阶段展示还原态魔方 ===== */
  useEffect(() => {
    if (initialized || !cubeRef.current) return
    const t = setTimeout(() => {
      cubeRef.current?.reset()
      setInitialized(true)
    }, 600)
    return () => clearTimeout(t)
  }, [initialized])

  /* ===== 阶段切换：重置魔方并播放初始打乱 ===== */
  useEffect(() => {
    // 确定当前阶段对应的初始打乱序列
    let initMoves: Move[] | null = null
    if (phase.startsWith('corner-') && phase !== 'corner-done') {
      initMoves = CORNER_INITIAL_MOVES
    } else if (phase.startsWith('edge-')) {
      initMoves = EDGE_INITIAL_MOVES
    }
    if (!initMoves || !cubeRef.current) return

    /* 重置 store 和 3D 场景 */
    storeReset()
    cubeRef.current.reset()
    setUserNotations([])
    setDone(false)
    setReady(false)
    setGuidedIdx(-1)

    /* 播放初始打乱动画 */
    let d = 200
    for (const m of initMoves) {
      setTimeout(() => cubeRef.current?.executeMove(moveToNotation(m)), d)
      d += 350
    }

    /* 动画结束后，根据子阶段决定下一步 */
    if (phase.endsWith('-guided')) {
      // 引导模式：启动逐步演示
      setTimeout(() => setGuidedIdx(0), d + 300)
    } else if (phase.endsWith('-practice')) {
      // 实操模式：标记为可操作
      setTimeout(() => setReady(true), d)
    }
    /* intro 阶段：不设置 ready，用户只观察 */
  }, [phase, storeReset, retryKey])

  /* ===== 引导动画：guidedIdx 变化时执行对应解法步 ===== */
  useEffect(() => {
    let moves: Move[] | null = null
    if (phase === 'corner-guided') moves = CORNER_SOLUTION_MOVES
    else if (phase === 'edge-guided') moves = EDGE_SOLUTION_MOVES
    if (!moves || guidedIdx < 0 || guidedIdx >= moves.length) return

    const t = setTimeout(() => {
      cubeRef.current?.executeMove(moveToNotation(moves![guidedIdx]))
    }, 500)
    return () => clearTimeout(t)
  }, [guidedIdx, phase])

  /* ===== 监听用户实操：检测魔方是否还原 ===== */
  useEffect(() => {
    if (!ready || done) return
    if (phase !== 'corner-practice' && phase !== 'edge-practice') return

    const initMoves = phase === 'corner-practice'
      ? CORNER_INITIAL_MOVES : EDGE_INITIAL_MOVES
    const offset = initMoves.length
    const newMoves = storeHistory.slice(offset)
    setUserNotations(newMoves.map(moveToNotation))

    /* 用户至少操作了一步，且魔方已还原 → 成功 */
    if (newMoves.length > 0 && isSolved(storeCubies)) {
      setDone(true)
      setStarVisible(true)
      // 角块完成 → corner-done，棱块完成 → done
      setTimeout(() => setPhase(phase === 'corner-practice' ? 'corner-done' : 'done'), 600)
    }
  }, [storeCubies, storeHistory, phase, done, ready])

  /* ===== 进度信息 ===== */
  const taskInfo = getTaskInfo(phase)

  /* ---- 渲染 ---- */
  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', paddingBottom: '2rem' }}>
      {/* 顶部状态条 */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '0.8rem 1.5rem',
        borderBottom: '1px solid var(--rule)',
        background: '#fff',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
          <Link to="/chapter/solve" style={{
            fontSize: '0.85rem', color: 'var(--ink2)', textDecoration: 'none',
          }}>
            ← 返回第6节
          </Link>
          <span style={{ fontWeight: 700 }}>复原引导</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
          {/* 步骤指示器 */}
          {[1, 2, 3].map((n) => (
            <div key={n} title={['白色十字', '白色角块', '中层棱块'][n - 1]} style={{
              width: '10px', height: '10px', borderRadius: '50%',
              background: n <= taskInfo.step ? 'var(--accent)' : 'var(--rule)',
              transition: 'background 0.3s ease',
            }} />
          ))}
          <span style={{ fontSize: '0.75rem', color: 'var(--muted)', marginLeft: '0.3rem' }}>
            步骤 {taskInfo.step}/{taskInfo.total}
          </span>
        </div>
      </div>

      {/* 双栏布局 */}
      <div style={{
        display: 'flex', gap: '1.5rem', padding: '1.5rem',
        maxWidth: '1100px', margin: '0 auto', alignItems: 'flex-start',
      }}>
        {/* 左：指引区 */}
        <div style={{ flex: 1, minWidth: 0 }}>
          <div className="card" style={{ marginBottom: '1rem' }}>
            {/* 标题 */}
            <h2 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '0.3rem' }}>
              {taskInfo.name}
            </h2>

            {/* 阶段标签（非 cross / done 阶段显示） */}
            {phase !== 'cross' && phase !== 'done' && (
              <div style={{ display: 'flex', gap: '0.4rem', marginBottom: '1rem' }}>
                {([
                  { k: 'intro', label: '介绍' },
                  { k: 'guided', label: '引导' },
                  { k: 'practice', label: '实操' },
                  { k: 'done', label: '完成' },
                ] as const).map((s) => {
                  const active = phase.includes('-' + s.k)
                  return (
                    <span key={s.k} style={{
                      padding: '0.15rem 0.6rem', borderRadius: '999px',
                      fontSize: '0.7rem', fontWeight: active ? 700 : 400,
                      background: active ? 'var(--accent-l)' : 'var(--bg2)',
                      color: active ? 'var(--accent-d)' : 'var(--muted)',
                    }}>
                      {s.label}
                    </span>
                  )
                })}
              </div>
            )}

            {/* ================================================================ */}
            {/* 阶段1：白色十字（仅观察，无需操作） */}
            {/* ================================================================ */}
            {phase === 'cross' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  复原魔方的第一步是完成<strong>白色十字</strong>——
                  让白色中心块四周的四个白色棱块全部归位。
                </p>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  这一步<strong>不需要记公式</strong>——你只要通过直觉把白色棱块逐个移到正确位置即可。
                  右侧魔方已处在白色十字完成的状态。
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: 'var(--accent-l)', borderRadius: '8px',
                  fontSize: '0.8rem', color: 'var(--accent-d)',
                }}>
                  <strong>概念对应</strong>：十字等同于在三维空间中确定了坐标轴的"基准方向"——
                  白色=底、黄色=顶、红色=前、橙色=后、蓝色=右、绿色=左。
                  这六个方向构成了魔方的<strong>方向指数坐标系</strong>（第1节内容）。
                </div>
                <button
                  className="btn btn-primary"
                  style={{ width: '100%' }}
                  onClick={() => setPhase('corner-intro')}
                >
                  下一步：复原角块 →
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 阶段2-介绍：白色角块 */}
            {/* ================================================================ */}
            {phase === 'corner-intro' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  白色十字已完成。接下来只剩最后一个角块需要归位。
                </p>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  我们将使用下面的操作——它是<strong>逆矩阵组合</strong>的经典应用：
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: 'var(--accent-l)', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '1rem', fontWeight: 700,
                  textAlign: 'center', color: 'var(--accent-d)',
                }}>
                  {CORNER_SOLUTION_MOVES.map(moveToNotation).join(' → ')}
                </div>
                <p style={{ fontSize: '0.8rem', color: 'var(--ink2)', marginBottom: '1rem' }}>
                  注意看初始状态和最终状态——这四步操作打乱时用了什么，解决时就按<strong>相反顺序</strong>逆向执行，
                  正好印证了第4节的逆序法则：(A·B)⁻¹ = B⁻¹·A⁻¹。
                </p>
                <button className="btn btn-primary" style={{ width: '100%' }} onClick={() => setPhase('corner-guided')}>
                  开始引导 →
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 阶段2-引导：白色角块 — 逐步演示 */}
            {/* ================================================================ */}
            {phase === 'corner-guided' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '1rem' }}>
                  魔方已回到初始状态。点击「下一步」观看每一步的效果：
                </p>
                {CORNER_GUIDED_STEPS.map((s, i) => (
                  <div key={i} style={{
                    padding: '0.5rem 0.8rem', marginBottom: '0.5rem',
                    borderRadius: '6px',
                    background: i === guidedIdx ? 'var(--accent-l)' : 'var(--bg2)',
                    borderLeft: '3px solid ' + (i === guidedIdx ? 'var(--accent)' : 'transparent'),
                  }}>
                    <span style={{ fontSize: '0.85rem', fontWeight: 600 }}>{s.notation}</span>
                    <span style={{ fontSize: '0.78rem', color: 'var(--ink2)', marginLeft: '0.6rem' }}>
                      {s.text}
                    </span>
                  </div>
                ))}
                {guidedIdx >= CORNER_SOLUTION_MOVES.length ? (
                  <div style={{ marginTop: '1rem' }}>
                    <p style={{
                      fontSize: '0.85rem', fontWeight: 700, color: 'var(--green)',
                      marginBottom: '0.8rem',
                    }}>
                      ✅ 角块已归位！接下来你亲手试试。
                    </p>
                    <button className="btn btn-primary" onClick={() => setPhase('corner-practice')}>
                      🎯 进入实操
                    </button>
                  </div>
                ) : (
                  <div style={{ display: 'flex', gap: '0.5rem', marginTop: '0.5rem' }}>
                    <button
                      className="btn btn-outline"
                      onClick={() => setGuidedIdx((p) => p + 1)}
                    >
                      {guidedIdx === -1 ? '开始演示' : '下一步 →'}
                    </button>
                    <button className="btn btn-outline" onClick={() => setPhase('corner-practice')}>
                      跳过引导
                    </button>
                  </div>
                )}
              </>
            )}

            {/* ================================================================ */}
            {/* 阶段2-实操：白色角块 — 亲手复原 */}
            {/* ================================================================ */}
            {phase === 'corner-practice' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  魔方已回到初始状态。请在右侧魔方上执行以下操作：
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: 'var(--accent-l)', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '1rem', fontWeight: 700,
                  textAlign: 'center', color: 'var(--accent-d)',
                }}>
                  {CORNER_SOLUTION_MOVES.map(moveToNotation).join(' → ')}
                </div>
                <div style={{ marginBottom: '1rem' }}>
                  <p style={{ fontSize: '0.75rem', color: 'var(--muted)', marginBottom: '0.4rem' }}>
                    你已执行：
                  </p>
                  <div style={{
                    padding: '0.4rem 0.8rem', borderRadius: '6px',
                    background: 'var(--bg2)', fontFamily: 'monospace',
                    fontSize: '0.85rem',
                    color: userNotations.length > 0 ? 'var(--accent)' : 'var(--muted)',
                  }}>
                    {userNotations.length > 0 ? userNotations.join(' → ') : '等待操作…'}
                  </div>
                </div>
                <button
                  className="btn btn-outline"
                  style={{ width: '100%' }}
                  onClick={() => setRetryKey((k) => k + 1)}
                >
                  重置重试
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 阶段2-完成：角块完成，过渡到棱块 */}
            {/* ================================================================ */}
            {phase === 'corner-done' && (
              <>
                {starVisible && (
                  <div style={{ textAlign: 'center', marginBottom: '1rem' }}>
                    <span style={{ fontSize: '3rem' }}>⭐</span>
                    <p style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--accent)', marginTop: '0.5rem' }}>
                      角块归位完成！
                    </p>
                  </div>
                )}
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  你刚用逆矩阵组合（R' D' R D）成功归位了一个角块。
                  这正好对应第4节的核心思想——撤销操作就是逆矩阵。
                </p>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '1rem' }}>
                  接下来难度升级：复原中层棱块，这次会用到<strong>三明治变换（共轭）</strong>——
                  把棱块先搬出来、调整、再塞回去，对应第6节的核心工具。
                </p>
                <button
                  className="btn btn-primary"
                  style={{ width: '100%' }}
                  onClick={() => setPhase('edge-intro')}
                >
                  下一步：复原中层棱块 →
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 阶段3-介绍：中层棱块 */}
            {/* ================================================================ */}
            {phase === 'edge-intro' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  白色面和底层角块已全部完成。
                  现在要处理<strong>中层棱块</strong>——位于魔方中层（第二层）的四个棱块。
                </p>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  右侧魔方已打乱：白色底完好，但有一个中层棱块被移到了顶层。
                  我们用下面的公式把它送回正确位置：
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: 'var(--accent-l)', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '1rem', fontWeight: 700,
                  textAlign: 'center', color: 'var(--accent-d)',
                }}>
                  {EDGE_SOLUTION_MOVES.map(moveToNotation).join(' → ')}
                </div>
                <p style={{ fontSize: '0.8rem', color: 'var(--ink2)', marginBottom: '1rem' }}>
                  这就是一个<strong>三明治变换（共轭）</strong>：把棱块从顶层搬到中层。
                  前半段（U R U' R'）腾出空间，后半段（U' F' U F）把棱块塞入并调正朝向。
                  结构是"打开→放入→关好"。
                </p>
                <button className="btn btn-primary" style={{ width: '100%' }} onClick={() => setPhase('edge-guided')}>
                  开始引导 →
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 阶段3-引导：中层棱块 — 逐步演示 */}
            {/* ================================================================ */}
            {phase === 'edge-guided' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.6rem' }}>
                  点击「下一步」观看每一步的效果：
                </p>
                {EDGE_GUIDED_STEPS.map((s, i) => (
                  <div key={i} style={{
                    padding: '0.4rem 0.6rem', marginBottom: '0.35rem',
                    borderRadius: '6px',
                    background: i === guidedIdx ? 'var(--accent-l)' : 'var(--bg2)',
                    borderLeft: '3px solid ' + (i === guidedIdx ? 'var(--accent)' : 'transparent'),
                  }}>
                    <span style={{ fontSize: '0.82rem', fontWeight: 600 }}>{s.notation}</span>
                    <span style={{ fontSize: '0.75rem', color: 'var(--ink2)', marginLeft: '0.5rem' }}>
                      {s.text}
                    </span>
                  </div>
                ))}
                {guidedIdx >= EDGE_SOLUTION_MOVES.length ? (
                  <div style={{ marginTop: '1rem' }}>
                    <p style={{
                      fontSize: '0.85rem', fontWeight: 700, color: 'var(--green)',
                      marginBottom: '0.8rem',
                    }}>
                      ✅ 棱块已归位！现在你亲手试试。
                    </p>
                    <button className="btn btn-primary" onClick={() => setPhase('edge-practice')}>
                      🎯 进入实操
                    </button>
                  </div>
                ) : (
                  <div style={{ display: 'flex', gap: '0.5rem', marginTop: '0.5rem' }}>
                    <button
                      className="btn btn-outline"
                      onClick={() => setGuidedIdx((p) => p + 1)}
                    >
                      {guidedIdx === -1 ? '开始演示' : '下一步 →'}
                    </button>
                    <button className="btn btn-outline" onClick={() => setPhase('edge-practice')}>
                      跳过引导
                    </button>
                  </div>
                )}
              </>
            )}

            {/* ================================================================ */}
            {/* 阶段3-实操：中层棱块 — 亲手复原 */}
            {/* ================================================================ */}
            {phase === 'edge-practice' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  魔方已回到初始状态。请在右侧魔方上执行以下操作：
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: 'var(--accent-l)', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '0.9rem', fontWeight: 700,
                  textAlign: 'center', color: 'var(--accent-d)',
                }}>
                  {EDGE_SOLUTION_MOVES.map(moveToNotation).join(' → ')}
                </div>
                <div style={{ marginBottom: '1rem' }}>
                  <p style={{ fontSize: '0.75rem', color: 'var(--muted)', marginBottom: '0.4rem' }}>
                    你已执行：
                  </p>
                  <div style={{
                    padding: '0.4rem 0.8rem', borderRadius: '6px',
                    background: 'var(--bg2)', fontFamily: 'monospace',
                    fontSize: '0.82rem',
                    color: userNotations.length > 0 ? 'var(--accent)' : 'var(--muted)',
                  }}>
                    {userNotations.length > 0 ? userNotations.join(' → ') : '等待操作…'}
                  </div>
                </div>
                <button
                  className="btn btn-outline"
                  style={{ width: '100%' }}
                  onClick={() => setRetryKey((k) => k + 1)}
                >
                  重置重试
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 全部完成 */}
            {/* ================================================================ */}
            {phase === 'done' && (
              <>
                {starVisible && (
                  <div style={{ textAlign: 'center', marginBottom: '1rem' }}>
                    <span style={{ fontSize: '3rem' }}>🎉</span>
                    <p style={{ fontSize: '1.2rem', fontWeight: 700, color: 'var(--accent)', marginTop: '0.5rem' }}>
                      全部完成！
                    </p>
                  </div>
                )}
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.5rem' }}>
                  你成功完成了三步骤：白色十字 → 白色角块（逆矩阵组合） → 中层棱块（三明治变换）。
                </p>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '1rem' }}>
                  <strong>你已经亲身体验了线代两大核心工具的实战应用</strong>，
                  剩余步骤（黄色面、顶层棱角归位）将在后续版本中使用更多群论工具继续指导。
                </p>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <Link to="/chapter/solve" className="btn btn-outline" style={{ flex: 1, textAlign: 'center', textDecoration: 'none' }}>
                    回到第6节
                  </Link>
                  <Link to="/playground" className="btn btn-primary" style={{ flex: 1, textAlign: 'center', textDecoration: 'none' }}>
                    巩固练习 →
                  </Link>
                </div>
              </>
            )}
          </div>
        </div>

        {/* 右：魔方 */}
        <div style={{ width: '420px', flexShrink: 0 }}>
          <div style={{
            height: '420px', borderRadius: 'var(--radius)',
            overflow: 'hidden', border: '1px solid var(--rule)',
          }}>
            <Cube3DView ref={cubeRef} />
          </div>
          <p style={{
            marginTop: '0.4rem', fontSize: '0.72rem', color: 'var(--muted)',
            textAlign: 'center',
          }}>
            左键点击面 = 逆时针 | 右键点击面 = 顺时针 | 空白拖拽 = 旋转视角
          </p>
        </div>
      </div>
    </div>
  )
}
