/* Generated by Trae Work */
import { useRef, useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import Cube3DView from '../components/cube3d/Cube3DView'
import type { Cube3DViewHandle } from '../components/cube3d/Cube3DView'
import { useCubeStore } from '../store/cubeStore'
import { isSolved } from '../lib/cubeLogic'
import type { Move } from '../types/cube'

/* ==================================================================== */
/*  常量定义                                                               */
/* ==================================================================== */

/** 教程阶段类型 */
type Phase =
  | 'cross'          /* 步骤1：白色十字 — 观察 */
  | 'corner-intro'   /* 步骤2：白色角块 — 介绍 */
  | 'corner-guided'  /* 步骤2：白色角块 — 引导演示 */
  | 'corner-practice'/* 步骤2：白色角块 — 实操 */
  | 'corner-done'    /* 步骤2：完成 */
  | 'edge-intro'     /* 步骤3：中层棱块 — 介绍 */
  | 'edge-guided'    /* 步骤3：中层棱块 — 引导演示 */
  | 'edge-practice'  /* 步骤3：中层棱块 — 实操 */
  | 'topcross-intro'    /* 步骤4：黄色十字 — 介绍 */
  | 'topcross-guided'   /* 步骤4：黄色十字 — 引导演示 */
  | 'topcross-practice' /* 步骤4：黄色十字 — 实操 */
  | 'edgeloc-intro'     /* 步骤5：棱块归位 — 介绍 */
  | 'edgeloc-guided'    /* 步骤5：棱块归位 — 引导演示 */
  | 'edgeloc-practice'  /* 步骤5：棱块归位 — 实操 */
  | 'cornerloc-intro'   /* 步骤6：角块归位 — 介绍 */
  | 'cornerloc-guided'  /* 步骤6：角块归位 — 引导演示 */
  | 'cornerloc-practice'/* 步骤6：角块归位 — 实操 */
  | 'orient-intro'      /* 步骤7：翻黄角 — 介绍 */
  | 'orient-guided'     /* 步骤7：翻黄角 — 引导演示 */
  | 'orient-practice'   /* 步骤7：翻黄角 — 实操 */
  | 'done'           /* 全部完成 */

/* ---- 白色角块常量（步骤2） ---- */

/** 初始打乱：D' → R' → D → R — 打乱一个角块 */
const CORNER_INITIAL_MOVES: Move[] = [
  { axis: 'y', layer: -1, direction: -1 }, // D'
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: -1, direction: 1 },  // D
  { axis: 'x', layer: 1, direction: 1 },   // R
]

/** 角块解法：R' → D' → R → D — CORNER_INITIAL_MOVES 的逆操作 */
const CORNER_SOLUTION_MOVES: Move[] = [
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: -1, direction: -1 }, // D'
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: -1, direction: 1 },  // D
]

const CORNER_GUIDED_STEPS = [
  { notation: "R'", text: '打开右面空间，准备接收角块' },
  { notation: "D'", text: '移动底层，将目标位置对准角块' },
  { notation: 'R', text: '角块进入正确位置' },
  { notation: 'D', text: '恢复底层，角块归位完成' },
]

/* ---- 中层棱块常量（步骤3） ---- */

/** 初始打乱：F' → U' → F → U → R → U → R' → U'
 *  这是 EDGE_SOLUTION_MOVES 的逆操作，把一个中层棱块移到顶层 */
const EDGE_INITIAL_MOVES: Move[] = [
  { axis: 'z', layer: 1, direction: -1 },  // F'
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'z', layer: 1, direction: 1 },   // F
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: 1, direction: -1 },  // U'
]

/** 棱块解法：U → R → U' → R' → U' → F' → U → F */
const EDGE_SOLUTION_MOVES: Move[] = [
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'z', layer: 1, direction: -1 },  // F'
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'z', layer: 1, direction: 1 },   // F
]

const EDGE_GUIDED_STEPS = [
  { notation: 'U', text: '将顶层目标棱块移到右前准备位置' },
  { notation: 'R', text: '打开右侧面，为棱块创造中层入口' },
  { notation: "U'", text: '沿顶层将棱块推入右侧开口' },
  { notation: "R'", text: '关闭右侧面，棱块被锁定到中层' },
  { notation: "U'", text: '恢复顶层位置' },
  { notation: "F'", text: '打开前面，为朝向调整做准备' },
  { notation: 'U', text: '调整顶层，棱块朝向修正' },
  { notation: 'F', text: '关闭前面，棱块完全归位' },
]

/* ---- 黄色十字常量（步骤4） ---- */

/** 初始打乱：随机4步制造顶面棱块错乱 */
const TOPCROSS_INITIAL_MOVES: Move[] = [
  { axis: 'z', layer: 1, direction: 1 },   // F
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: -1 },  // R'
]

/** 顶面十字公式：F R U R' U' F' */
const TOPCROSS_SOLUTION_MOVES: Move[] = [
  { axis: 'z', layer: 1, direction: 1 },   // F
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'z', layer: 1, direction: -1 },  // F'
]

const TOPCROSS_GUIDED_STEPS = [
  { notation: 'F', text: 'F：前面顺时针 — 交换子开启，"推"到前面' },
  { notation: 'R', text: 'R：右面顺时针 — 核心操作，翻转顶层棱块朝向' },
  { notation: 'U', text: 'U：上面顺时针 — 移动目标棱块位置' },
  { notation: "R'", text: "R'：右面逆时针 — 开始搬回来" },
  { notation: "U'", text: "U'：上面逆时针 — 继续搬回来" },
  { notation: "F'", text: "F'：交换子完成 — 观察顶层黄色棱块朝向" },
]

/* ---- 黄色棱块归位（步骤5）常量 ---- */

/** 步骤5 初始打乱 */
const EDGELOC_INITIAL_MOVES: Move[] = [
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'x', layer: 1, direction: 1 },   // R
]

/** 步骤5-棱块归位解法：R U' R U R U R U' R' U' R2 */
const EDGELOC_SOLUTION_MOVES: Move[] = [
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'x', layer: 1, direction: 1 },   // R2 part 1
  { axis: 'x', layer: 1, direction: 1 },   // R2 part 2
]

const EDGELOC_GUIDED_STEPS = [
  { notation: 'R', text: 'R：启动棱块置换序列' },
  { notation: "U'", text: "U'：位置准备" },
  { notation: 'R', text: 'R：继续置换节奏' },
  { notation: 'U', text: 'U：循环推进' },
  { notation: 'R', text: 'R：累积置换效应' },
  { notation: 'U', text: 'U：持续循环' },
  { notation: 'R', text: 'R：关键中间位置' },
  { notation: "U'", text: "U'：反向轨道回位" },
  { notation: "R'", text: "R'：开始闭合，矩阵转置" },
  { notation: "U'", text: "U'：配合闭合节奏" },
  { notation: 'R2', text: 'R2：180°旋转 — 三个黄色棱块顺时针轮换' },
]

/* ---- 黄色角块归位（步骤6）常量 ---- */

/** 步骤6 初始打乱 */
const CORNERLOC_INITIAL_MOVES: Move[] = [
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'x', layer: -1, direction: -1 }, // L' (axis x layer -1 direction -1)
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'x', layer: -1, direction: 1 },  // L
]

/** 步骤6-角块归位解法：U R U' L' U R' U' L */
const CORNERLOC_SOLUTION_MOVES: Move[] = [
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'x', layer: -1, direction: -1 }, // L'
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: 1, direction: -1 },  // U'
  { axis: 'x', layer: -1, direction: 1 },  // L
]

const CORNERLOC_GUIDED_STEPS = [
  { notation: 'U', text: 'U：目标角块移入"待处理位"' },
  { notation: 'R', text: 'R：核心操作启动' },
  { notation: "U'", text: "U'：位置调整" },
  { notation: "L'", text: "L'：换到另一个角块" },
  { notation: 'U', text: 'U：返回交换路径' },
  { notation: "R'", text: "R'：闭合，第一个角块抵达" },
  { notation: "U'", text: "U'：为第二个角块腾出空间" },
  { notation: 'L', text: 'L：第二个角块滑入 — 三个角块互换位置' },
]

/* ---- 翻黄角（步骤7）常量 ---- */

/** 步骤7 初始打乱 */
const ORIENT_INITIAL_MOVES: Move[] = [
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: 1, direction: 1 },   // U
]

/** 步骤7-翻黄角（Sune）：R U R' U R U2 R' */
const ORIENT_SOLUTION_MOVES: Move[] = [
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: -1 },  // R'
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'x', layer: 1, direction: 1 },   // R
  { axis: 'y', layer: 1, direction: 1 },   // U
  { axis: 'y', layer: 1, direction: 1 },   // U2 part 2
  { axis: 'x', layer: 1, direction: -1 },  // R'
]

const ORIENT_GUIDED_STEPS = [
  { notation: 'R', text: 'R："打开右面"，为后续操作准备空间' },
  { notation: 'U', text: 'U：将目标角块移入操作区' },
  { notation: "R'", text: 'R\'："关上右面"（逆变换），不是简单撤销' },
  { notation: 'U', text: 'U：进一步调整角块朝向' },
  { notation: 'R', text: 'R：再次打开右面，准备第二轮' },
  { notation: 'U2', text: 'U2：180°旋转 = 两个连续90°，不是矩阵平方' },
  { notation: "R'", text: "R'：最终关闭，完成一个子角翻正" },
]

/* ---- 工具函数 ---- */

/** Move → 记法文本 */
function moveToNotation(m: Move): string {
  const faceMap: Record<string, Record<string, string>> = {
    x: { '1': 'R', '-1': 'L' },
    y: { '1': 'U', '-1': 'D' },
    z: { '1': 'F', '-1': 'B' },
  }
  const face = faceMap[m.axis]?.[String(m.layer)] ?? m.axis.toUpperCase()
  return m.direction === 1 ? face : face + "'"
}

/** 获取当前阶段的元信息 */
function getTaskInfo(phase: Phase): { step: number; total: number; name: string } {
  if (phase === 'cross') return { step: 1, total: 7, name: '白色十字' }
  const isCorner = phase === 'corner-intro' || phase === 'corner-guided' || phase === 'corner-practice' || phase === 'corner-done'
  if (isCorner) return { step: 2, total: 7, name: '白色角块' }
  const isEdge = phase === 'edge-intro' || phase === 'edge-guided' || phase === 'edge-practice'
  if (isEdge) return { step: 3, total: 7, name: '中层棱块' }
  const isTopcross = phase === 'topcross-intro' || phase === 'topcross-guided' || phase === 'topcross-practice'
  if (isTopcross) return { step: 4, total: 7, name: '黄色十字' }
  const isEdgeloc = phase === 'edgeloc-intro' || phase === 'edgeloc-guided' || phase === 'edgeloc-practice'
  if (isEdgeloc) return { step: 5, total: 7, name: '棱块归位' }
  const isCornerloc = phase === 'cornerloc-intro' || phase === 'cornerloc-guided' || phase === 'cornerloc-practice'
  if (isCornerloc) return { step: 6, total: 7, name: '角块归位' }
  const isOrient = phase === 'orient-intro' || phase === 'orient-guided' || phase === 'orient-practice'
  if (isOrient) return { step: 7, total: 7, name: '翻黄角' }
  return { step: 7, total: 7, name: '全部完成' }
}

/** 判断当前阶段是否属于角块步骤 */
function isCornerPhase(phase: Phase): boolean {
  return phase === 'corner-intro' || phase === 'corner-guided' || phase === 'corner-practice' || phase === 'corner-done'
}

/** 判断当前阶段是否属于棱块步骤 */
function isEdgePhase(phase: Phase): boolean {
  return phase === 'edge-intro' || phase === 'edge-guided' || phase === 'edge-practice'
}

/** 判断当前阶段是否属于顶面十字步骤 */
function isTopcrossPhase(phase: Phase): boolean {
  return phase === 'topcross-intro' || phase === 'topcross-guided' || phase === 'topcross-practice'
}

function isEdgelocPhase(phase: Phase): boolean {
  return phase === 'edgeloc-intro' || phase === 'edgeloc-guided' || phase === 'edgeloc-practice'
}

function isCornerlocPhase(phase: Phase): boolean {
  return phase === 'cornerloc-intro' || phase === 'cornerloc-guided' || phase === 'cornerloc-practice'
}

function isOrientPhase(phase: Phase): boolean {
  return phase === 'orient-intro' || phase === 'orient-guided' || phase === 'orient-practice'
}

/* ==================================================================== */
/*  组件                                                                  */
/* ==================================================================== */

export default function Tutorial() {
  /* ---- 引用 ---- */
  const cubeRef = useRef<Cube3DViewHandle>(null)

  /* ---- 本地状态 ---- */
  const [phase, setPhase] = useState<Phase>('cross')
  const [guidedIdx, setGuidedIdx] = useState(-1)
  const [initialized, setInitialized] = useState(false)
  const [taskDone, setTaskDone] = useState(false)    // 当前任务是否完成
  const [starVisible, setStarVisible] = useState(false)
  const [userNotations, setUserNotations] = useState<string[]>([])
  const [ready, setReady] = useState(false)        // 初始动画播放完毕，可以开始操作
  const [retryKey, setRetryKey] = useState(0)        // 用于强制重新触发 reset 操作

  /* ---- Zustand store ---- */
  const storeHistory = useCubeStore((s) => s.history)
  const storeCubies = useCubeStore((s) => s.cubies)
  const storeReset = useCubeStore((s) => s.reset)

  /* ===== 初始化：cross 阶段展示还原态魔方 ===== */
  useEffect(() => {
    if (initialized || !cubeRef.current) return
    const t = setTimeout(() => {
      cubeRef.current?.reset()
      setInitialized(true)
    }, 600)
    return () => clearTimeout(t)
  }, [initialized])

  /* ===== 阶段切换：重置魔方并播放初始打乱 ===== */
  useEffect(() => {
    // 确定当前阶段对应的初始打乱序列
    let initMoves: Move[] | null = null
    if (isCornerPhase(phase) && phase !== 'corner-done') {
      initMoves = CORNER_INITIAL_MOVES
    } else if (isEdgePhase(phase)) {
      initMoves = EDGE_INITIAL_MOVES
    } else if (isTopcrossPhase(phase)) {
      initMoves = TOPCROSS_INITIAL_MOVES
    } else if (isEdgelocPhase(phase)) {
      initMoves = EDGELOC_INITIAL_MOVES
    } else if (isCornerlocPhase(phase)) {
      initMoves = CORNERLOC_INITIAL_MOVES
    } else if (isOrientPhase(phase)) {
      initMoves = ORIENT_INITIAL_MOVES
    }
    if (!initMoves || !cubeRef.current) return

    /* 重置 store 和 3D 场景 */
    storeReset()
    cubeRef.current.reset()
    setUserNotations([])
    setTaskDone(false)
    setReady(false)
    setGuidedIdx(-1)

    /* 播放初始打乱动画 */
    let d = 400
    for (const m of initMoves) {
      setTimeout(() => cubeRef.current?.executeMove(moveToNotation(m)), d)
      d += 350
    }

    /* 动画结束后，根据子阶段决定下一步 */
    if (phase === 'corner-guided' || phase === 'edge-guided' || phase === 'topcross-guided' || phase === 'edgeloc-guided' || phase === 'cornerloc-guided' || phase === 'orient-guided') {
      // 引导模式：启动逐步演示
      setTimeout(() => setGuidedIdx(0), d + 300)
    } else if (phase === 'corner-practice' || phase === 'edge-practice' || phase === 'topcross-practice' || phase === 'edgeloc-practice' || phase === 'cornerloc-practice' || phase === 'orient-practice') {
      // 实操模式：标记为可操作
      setTimeout(() => setReady(true), d)
    }
    /* intro 阶段：不设置 ready，用户只观察 */
  }, [phase, storeReset, retryKey])

  /* ===== 引导动画：guidedIdx 变化时执行对应解法步 ===== */
  useEffect(() => {
    let moves: Move[] | null = null
    if (phase === 'corner-guided') moves = CORNER_SOLUTION_MOVES
    else if (phase === 'edge-guided') moves = EDGE_SOLUTION_MOVES
    else if (phase === 'topcross-guided') moves = TOPCROSS_SOLUTION_MOVES
    else if (phase === 'edgeloc-guided') moves = EDGELOC_SOLUTION_MOVES
    else if (phase === 'cornerloc-guided') moves = CORNERLOC_SOLUTION_MOVES
    else if (phase === 'orient-guided') moves = ORIENT_SOLUTION_MOVES
    if (!moves || guidedIdx < 0 || guidedIdx >= moves.length) return

    const t = setTimeout(() => {
      cubeRef.current?.executeMove(moveToNotation(moves![guidedIdx]))
    }, 1000)
    return () => clearTimeout(t)
  }, [guidedIdx, phase])

  /* ===== 监听用户实操：检测魔方是否还原 ===== */
  useEffect(() => {
    if (!ready || taskDone) return
    if (phase !== 'corner-practice' && phase !== 'edge-practice' && phase !== 'topcross-practice' && phase !== 'edgeloc-practice' && phase !== 'cornerloc-practice' && phase !== 'orient-practice') return

    const initMoves = phase === 'corner-practice'
      ? CORNER_INITIAL_MOVES : phase === 'edge-practice'
      ? EDGE_INITIAL_MOVES : phase === 'topcross-practice'
      ? TOPCROSS_INITIAL_MOVES : phase === 'edgeloc-practice'
      ? EDGELOC_INITIAL_MOVES : phase === 'cornerloc-practice'
      ? CORNERLOC_INITIAL_MOVES : ORIENT_INITIAL_MOVES
    const offset = initMoves.length
    const newMoves = storeHistory.slice(offset)
    setUserNotations(newMoves.map(moveToNotation))

    /* 用户至少操作了一步，且魔方已还原 → 成功 */
    if (newMoves.length > 0 && isSolved(storeCubies)) {
      setTaskDone(true)
      setStarVisible(true)
      // 依次推进：corner→edge→topcross→edgeloc→cornerloc→orient→done
      setTimeout(() => setPhase(
        phase === 'corner-practice' ? 'corner-done' :
        phase === 'edge-practice' ? 'topcross-intro' :
        phase === 'topcross-practice' ? 'edgeloc-intro' :
        phase === 'edgeloc-practice' ? 'cornerloc-intro' :
        phase === 'cornerloc-practice' ? 'orient-intro' :
        'done'
      ), 600)
    }
  }, [storeCubies, storeHistory, phase, taskDone, ready])

  /* ===== 进度信息 ===== */
  const taskInfo = getTaskInfo(phase)

  /* ---- 渲染 ---- */
  return (
    <div style={{ background: 'var(--bg)', paddingBottom: '2rem' }}>
      {/* 子页面顶栏（非固定，内容流中） */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '0.6rem 1.5rem',
        borderBottom: '1px solid var(--rule)',
        background: '#fff',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
          <Link to="/chapter/solve" style={{
            fontSize: '0.85rem', color: 'var(--ink2)', textDecoration: 'none',
          }}>
            ← 返回第6节
          </Link>
          <span style={{ fontWeight: 700 }}>复原引导</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
          {/* 步骤指示器 */}
          {[1, 2, 3, 4, 5, 6, 7].map((n) => {
            const isCurrent = n === taskInfo.step
            const isDone = n < taskInfo.step
            return (
              <div key={n} title={['白色十字', '白色角块', '中层棱块', '黄色十字', '棱块归位', '角块归位', '翻黄角'][n - 1]} style={{
                width: isCurrent ? '12px' : '10px',
                height: isCurrent ? '12px' : '10px',
                borderRadius: '50%',
                background: isDone ? '#10B981' : isCurrent ? 'var(--accent)' : 'var(--rule)',
                border: isCurrent ? '2px solid var(--accent)' : isDone ? '2px solid #10B981' : '2px solid var(--rule)',
                transition: 'all 0.3s ease',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}>
                {isDone && <span style={{ fontSize: '7px', color: '#fff', fontWeight: 700 }}>✓</span>}
              </div>
            )
          })}
          <span style={{ fontSize: '0.75rem', color: 'var(--muted)', marginLeft: '0.3rem' }}>
            步骤 {taskInfo.step}/{taskInfo.total}
          </span>
        </div>
      </div>

      {/* 双栏布局 */}
      <div style={{
        display: 'flex', gap: '1.5rem', padding: '1.5rem',
        maxWidth: '1100px', margin: '0 auto', alignItems: 'flex-start',
      }}>
        {/* 左：指引区 */}
        <div style={{ flex: 1, minWidth: 0 }}>
          <div className="card" style={{ marginBottom: '1rem' }}>
            {/* 标题 */}
            <h2 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '0.3rem' }}>
              {taskInfo.name}
            </h2>

            {/* 阶段标签（非 cross / done 阶段显示） */}
            {phase !== 'cross' && phase !== 'done' && (
              <div style={{ display: 'flex', gap: '0.4rem', marginBottom: '1rem' }}>
                {([
                  { k: 'intro', label: '介绍' },
                  { k: 'guided', label: '引导' },
                  { k: 'practice', label: '实操' },
                  { k: 'done', label: '完成' },
                ] as const).map((s) => {
                  const active = phase === `corner-${s.k}` || phase === `edge-${s.k}` || phase === `topcross-${s.k}` || phase === `edgeloc-${s.k}` || phase === `cornerloc-${s.k}` || phase === `orient-${s.k}`
                  return (
                    <span key={s.k} style={{
                      padding: '0.15rem 0.6rem', borderRadius: '999px',
                      fontSize: '0.7rem', fontWeight: active ? 700 : 400,
                      background: active ? 'var(--accent-l)' : 'var(--bg2)',
                      color: active ? 'var(--accent-d)' : 'var(--muted)',
                    }}>
                      {s.label}
                    </span>
                  )
                })}
              </div>
            )}

            {/* ================================================================ */}
            {/* 阶段1：白色十字（仅观察，无需操作） */}
            {/* ================================================================ */}
            {phase === 'cross' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  复原魔方的第一步是完成<strong>白色十字</strong>——
                  让白色中心块四周的四个白色棱块全部归位。
                </p>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  这一步<strong>不需要记公式</strong>——你只要通过直觉把白色棱块逐个移到正确位置即可。
                  右侧魔方已处在白色十字完成的状态。
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: 'var(--accent-l)', borderRadius: '8px',
                  fontSize: '0.8rem', color: 'var(--accent-d)',
                }}>
                  <strong>概念对应</strong>：十字等同于在三维空间中确定了坐标轴的"基准方向"——
                  白色=底、黄色=顶、红色=前、橙色=后、蓝色=右、绿色=左。
                  这六个方向构成了魔方的<strong>方向指数坐标系</strong>（第1节内容）。
                </div>
                <button
                  className="btn btn-primary"
                  style={{ width: '100%' }}
                  onClick={() => setPhase('corner-intro')}
                >
                  下一步：复原角块 →
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 阶段2-介绍：白色角块 */}
            {/* ================================================================ */}
            {phase === 'corner-intro' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  白色十字已完成。接下来只剩最后一个角块需要归位。
                </p>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  我们将使用下面的操作——它是<strong>逆序列法则</strong>的直接应用：
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: 'var(--accent-l)', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '1rem', fontWeight: 700,
                  textAlign: 'center', color: 'var(--accent-d)',
                }}>
                  {CORNER_SOLUTION_MOVES.map(moveToNotation).join(' → ')}
                </div>
                <p style={{ fontSize: '0.8rem', color: 'var(--ink2)', marginBottom: '1rem' }}>
                  注意看初始状态和最终状态——这四步操作打乱时用了什么，解决时就按<strong>相反顺序</strong>逆向执行，
                  这就是逆序列法则：(A·B·C·D)⁻¹ = D⁻¹·C⁻¹·B⁻¹·A⁻¹，后做的先撤销。
                </p>
                <button className="btn btn-primary" style={{ width: '100%' }} onClick={() => setPhase('corner-guided')}>
                  开始引导 →
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 阶段2-引导：白色角块 — 逐步演示 */}
            {/* ================================================================ */}
            {phase === 'corner-guided' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '1rem' }}>
                  魔方已回到初始状态。点击「下一步」观看每一步的效果：
                </p>
                {CORNER_GUIDED_STEPS.map((s, i) => (
                  <div key={i} style={{
                    padding: '0.5rem 0.8rem', marginBottom: '0.5rem',
                    borderRadius: '6px',
                    background: i === guidedIdx ? 'var(--accent-l)' : 'var(--bg2)',
                    borderLeft: '3px solid ' + (i === guidedIdx ? 'var(--accent)' : 'transparent'),
                  }}>
                    <span style={{ fontSize: '0.85rem', fontWeight: 600 }}>{s.notation}</span>
                    <span style={{ fontSize: '0.78rem', color: 'var(--ink2)', marginLeft: '0.6rem' }}>
                      {s.text}
                    </span>
                  </div>
                ))}
                {guidedIdx >= CORNER_SOLUTION_MOVES.length ? (
                  <div style={{ marginTop: '1rem' }}>
                    <p style={{
                      fontSize: '0.85rem', fontWeight: 700, color: 'var(--green)',
                      marginBottom: '0.8rem',
                    }}>
                      ✅ 角块已归位！接下来你亲手试试。
                    </p>
                    <button className="btn btn-primary" onClick={() => setPhase('corner-practice')}>
                      🎯 进入实操
                    </button>
                  </div>
                ) : (
                  <div style={{ display: 'flex', gap: '0.5rem', marginTop: '0.5rem' }}>
                    <button
                      className="btn btn-outline"
                      onClick={() => setGuidedIdx((p) => p + 1)}
                    >
                      {guidedIdx === -1 ? '开始演示' : '下一步 →'}
                    </button>
                    <button className="btn btn-outline" onClick={() => setPhase('corner-practice')}>
                      跳过引导
                    </button>
                  </div>
                )}
              </>
            )}

            {/* ================================================================ */}
            {/* 阶段2-实操：白色角块 — 亲手复原 */}
            {/* ================================================================ */}
            {phase === 'corner-practice' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  魔方已回到初始状态。请在右侧魔方上执行以下操作：
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: 'var(--accent-l)', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '1rem', fontWeight: 700,
                  textAlign: 'center', color: 'var(--accent-d)',
                }}>
                  {CORNER_SOLUTION_MOVES.map(moveToNotation).join(' → ')}
                </div>
                <div style={{ marginBottom: '1rem' }}>
                  <p style={{ fontSize: '0.75rem', color: 'var(--muted)', marginBottom: '0.4rem' }}>
                    你已执行：
                  </p>
                  <div style={{
                    padding: '0.4rem 0.8rem', borderRadius: '6px',
                    background: 'var(--bg2)', fontFamily: 'monospace',
                    fontSize: '0.85rem',
                    color: userNotations.length > 0 ? 'var(--accent)' : 'var(--muted)',
                  }}>
                    {userNotations.length > 0 ? userNotations.join(' → ') : '等待操作…'}
                  </div>
                </div>
                <button
                  className="btn btn-outline"
                  style={{ width: '100%' }}
                  onClick={() => setRetryKey((k) => k + 1)}
                >
                  重置重试
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 阶段2-完成：角块完成，过渡到棱块 */}
            {/* ================================================================ */}
            {phase === 'corner-done' && (
              <>
                {starVisible && (
                  <div style={{ textAlign: 'center', marginBottom: '1rem' }}>
                    <span style={{ fontSize: '3rem' }}>⭐</span>
                    <p style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--accent)', marginTop: '0.5rem' }}>
                      角块归位完成！
                    </p>
                  </div>
                )}
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  你刚用逆序列法则（R' D' R D）成功归位了一个角块。
                  这正好对应第4节的核心思想——把打乱步骤反过来执行，后做的先撤销。
                </p>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '1rem' }}>
                  接下来难度升级：复原中层棱块，这次会用到<strong>组合操作</strong>——
                  前后两段各使用一次共轭变换（P·A·P'）：先腾出空间，再塞入棱块。
                </p>
                <button
                  className="btn btn-primary"
                  style={{ width: '100%' }}
                  onClick={() => setPhase('edge-intro')}
                >
                  下一步：复原中层棱块 →
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 阶段3-介绍：中层棱块 */}
            {/* ================================================================ */}
            {phase === 'edge-intro' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  白色面和底层角块已全部完成。
                  现在要处理<strong>中层棱块</strong>——位于魔方中层（第二层）的四个棱块。
                </p>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  右侧魔方已打乱：白色底完好，但有一个中层棱块被移到了顶层。
                  我们用下面的公式把它送回正确位置：
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: 'var(--accent-l)', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '1rem', fontWeight: 700,
                  textAlign: 'center', color: 'var(--accent-d)',
                }}>
                  {EDGE_SOLUTION_MOVES.map(moveToNotation).join(' → ')}
                </div>
                <p style={{ fontSize: '0.8rem', color: 'var(--ink2)', marginBottom: '1rem' }}>
                  这是一个<strong>组合操作</strong>：前后两段各使用一次共轭变换（P·A·P'）。
                  前半段 U R U' R' 把棱块从顶层移到右层（P=U, A=R, P'=U'·R'），
                  后半段 U' F' U F 把棱块从右层推入中层（P=U', A=F', P'=U·F）。
                  结构是"打开→放入→关好"。
                </p>
                <button className="btn btn-primary" style={{ width: '100%' }} onClick={() => setPhase('edge-guided')}>
                  开始引导 →
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 阶段3-引导：中层棱块 — 逐步演示 */}
            {/* ================================================================ */}
            {phase === 'edge-guided' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.6rem' }}>
                  点击「下一步」观看每一步的效果：
                </p>
                {EDGE_GUIDED_STEPS.map((s, i) => (
                  <div key={i} style={{
                    padding: '0.4rem 0.6rem', marginBottom: '0.35rem',
                    borderRadius: '6px',
                    background: i === guidedIdx ? 'var(--accent-l)' : 'var(--bg2)',
                    borderLeft: '3px solid ' + (i === guidedIdx ? 'var(--accent)' : 'transparent'),
                  }}>
                    <span style={{ fontSize: '0.82rem', fontWeight: 600 }}>{s.notation}</span>
                    <span style={{ fontSize: '0.75rem', color: 'var(--ink2)', marginLeft: '0.5rem' }}>
                      {s.text}
                    </span>
                  </div>
                ))}
                {guidedIdx >= EDGE_SOLUTION_MOVES.length ? (
                  <div style={{ marginTop: '1rem' }}>
                    <p style={{
                      fontSize: '0.85rem', fontWeight: 700, color: 'var(--green)',
                      marginBottom: '0.8rem',
                    }}>
                      ✅ 棱块已归位！现在你亲手试试。
                    </p>
                    <button className="btn btn-primary" onClick={() => setPhase('edge-practice')}>
                      🎯 进入实操
                    </button>
                  </div>
                ) : (
                  <div style={{ display: 'flex', gap: '0.5rem', marginTop: '0.5rem' }}>
                    <button
                      className="btn btn-outline"
                      onClick={() => setGuidedIdx((p) => p + 1)}
                    >
                      {guidedIdx === -1 ? '开始演示' : '下一步 →'}
                    </button>
                    <button className="btn btn-outline" onClick={() => setPhase('edge-practice')}>
                      跳过引导
                    </button>
                  </div>
                )}
              </>
            )}

            {/* ================================================================ */}
            {/* 阶段3-实操：中层棱块 — 亲手复原 */}
            {/* ================================================================ */}
            {phase === 'edge-practice' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  魔方已回到初始状态。请在右侧魔方上执行以下操作：
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: 'var(--accent-l)', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '0.9rem', fontWeight: 700,
                  textAlign: 'center', color: 'var(--accent-d)',
                }}>
                  {EDGE_SOLUTION_MOVES.map(moveToNotation).join(' → ')}
                </div>
                <div style={{ marginBottom: '1rem' }}>
                  <p style={{ fontSize: '0.75rem', color: 'var(--muted)', marginBottom: '0.4rem' }}>
                    你已执行：
                  </p>
                  <div style={{
                    padding: '0.4rem 0.8rem', borderRadius: '6px',
                    background: 'var(--bg2)', fontFamily: 'monospace',
                    fontSize: '0.82rem',
                    color: userNotations.length > 0 ? 'var(--accent)' : 'var(--muted)',
                  }}>
                    {userNotations.length > 0 ? userNotations.join(' → ') : '等待操作…'}
                  </div>
                </div>
                <button
                  className="btn btn-outline"
                  style={{ width: '100%' }}
                  onClick={() => setRetryKey((k) => k + 1)}
                >
                  重置重试
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 黄色十字 — 介绍 */}
            {/* ================================================================ */}
            {phase === 'topcross-intro' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  现在底层和中层已完成，只剩黄色面（顶层）。
                  黄色十字是一次"翻转"操作的核心：用<strong>交换子 F R U R' U' F'</strong> 翻转顶层棱块朝向。
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: '#FEF3C7', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '0.85rem',
                  textAlign: 'center', color: '#B45309',
                }}>
                  F R U R' U' F'
                </div>
                <ul style={{ fontSize: '0.82rem', color: 'var(--ink)', paddingLeft: '1.2rem', marginBottom: '1rem' }}>
                  <li style={{ marginBottom: '0.3rem' }}>这是<strong>交换子</strong>的经典结构：F·R·U·R'·U'·F'</li>
                  <li style={{ marginBottom: '0.3rem' }}>前半段 F·R·U·R'·U' = 打开操作空间</li>
                  <li style={{ marginBottom: '0.3rem' }}>后半段 F' = 关闭回来，只改变顶层棱块朝向</li>
                  <li>交换子的核心思想：<strong>打开→操作→关上</strong></li>
                </ul>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <button className="btn btn-primary" onClick={() => setPhase('topcross-guided')}>
                    看引导演示
                  </button>
                  <button className="btn btn-outline" onClick={() => setPhase('topcross-practice')}>
                    直接实操
                  </button>
                </div>
              </>
            )}

            {/* 黄色十字 — 引导 */}
            {phase === 'topcross-guided' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  观察黄色十字交换子的逐步动画：
                </p>
                {/* 步骤指示条 */}
                <div style={{ display: 'flex', gap: '0.25rem', marginBottom: '0.8rem', flexWrap: 'wrap' }}>
                  {TOPCROSS_GUIDED_STEPS.map((s, i) => (
                    <div key={i} style={{
                      padding: '0.2rem 0.5rem', borderRadius: '6px',
                      fontSize: '0.72rem',
                      background: i === guidedIdx ? '#FEF3C7' : (guidedIdx > i ? '#DCFCE7' : 'var(--bg2)'),
                      borderLeft: '3px solid ' + (i === guidedIdx ? '#F59E0B' : 'transparent'),
                      transition: 'all 0.3s ease',
                    }}>
                      <strong style={{ fontFamily: 'monospace' }}>{s.notation}</strong>
                    </div>
                  ))}
                </div>
                {TOPCROSS_GUIDED_STEPS.map((s, i) => (
                  <p key={i} style={{
                    fontSize: '0.78rem', color: i === guidedIdx ? 'var(--ink)' : 'var(--muted)',
                    fontWeight: i === guidedIdx ? 600 : 400,
                    marginBottom: i < TOPCROSS_GUIDED_STEPS.length - 1 ? '0.2rem' : '0.8rem',
                  }}>
                    {i + 1}. {s.text}
                  </p>
                ))}
                {guidedIdx >= TOPCROSS_GUIDED_STEPS.length - 1 && (
                  <>
                    <div style={{
                      padding: '0.5rem 0.8rem', borderRadius: '6px',
                      background: '#DCFCE7', fontSize: '0.82rem', marginBottom: '0.6rem',
                    }}>
                      <span style={{ fontWeight: 700, color: '#16A34A' }}>交换子完成</span>
                      <span style={{ color: 'var(--ink2)', marginLeft: '0.4rem' }}>
                        黄色十字出现。这就是 F R U R' U' F' 的威力。
                      </span>
                    </div>
                    <button className="btn btn-primary" onClick={() => setPhase('topcross-practice')}>
                      亲自试试 →
                    </button>
                  </>
                )}
              </>
            )}

            {/* 黄色十字 — 实操 */}
            {phase === 'topcross-practice' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  魔方已回到初始状态。请执行以下交换子：
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: '#FEF3C7', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '0.9rem', fontWeight: 700,
                  textAlign: 'center', color: '#B45309',
                }}>
                  {TOPCROSS_SOLUTION_MOVES.map(moveToNotation).join(' → ')}
                </div>
                <div style={{ marginBottom: '1rem' }}>
                  <p style={{ fontSize: '0.75rem', color: 'var(--muted)', marginBottom: '0.4rem' }}>
                    你已执行：
                  </p>
                  <div style={{
                    padding: '0.4rem 0.8rem', borderRadius: '6px',
                    background: 'var(--bg2)', fontFamily: 'monospace',
                    fontSize: '0.82rem',
                    color: userNotations.length > 0 ? 'var(--accent)' : 'var(--muted)',
                  }}>
                    {userNotations.length > 0 ? userNotations.join(' → ') : '等待操作…'}
                  </div>
                </div>
                <button
                  className="btn btn-outline"
                  style={{ width: '100%' }}
                  onClick={() => setRetryKey((k) => k + 1)}
                >
                  重置重试
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 棱块归位（步骤5）— 介绍 */}
            {/* ================================================================ */}
            {phase === 'edgeloc-intro' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  黄色十字完成后，现在把黄色棱块移到正确位置。
                  这是一个<strong>纯置换</strong>操作——只改变棱块的位置，不改变朝向。
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: '#FEF3C7', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '0.85rem',
                  textAlign: 'center', color: '#B45309',
                }}>
                  R U' R U R U R U' R' U' R2
                </div>
                <ul style={{ fontSize: '0.82rem', color: 'var(--ink)', paddingLeft: '1.2rem', marginBottom: '1rem' }}>
                  <li style={{ marginBottom: '0.3rem' }}>这是<strong>全排列群</strong>的经典操作——只改变位置不改朝向</li>
                  <li style={{ marginBottom: '0.3rem' }}>公式有 11 步，但逻辑清晰：累积置换效应 → 逆向闭合</li>
                  <li>R2（180°）不是矩阵平方，是两个连续 90° 旋转</li>
                </ul>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <button className="btn btn-primary" onClick={() => setPhase('edgeloc-guided')}>
                    看引导演示
                  </button>
                  <button className="btn btn-outline" onClick={() => setPhase('edgeloc-practice')}>
                    直接实操
                  </button>
                </div>
              </>
            )}

            {/* 棱块归位 — 引导 */}
            {phase === 'edgeloc-guided' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  观察棱块置换的逐步动画：
                </p>
                <div style={{ display: 'flex', gap: '0.25rem', marginBottom: '0.8rem', flexWrap: 'wrap' }}>
                  {EDGELOC_GUIDED_STEPS.map((s, i) => (
                    <div key={i} style={{
                      padding: '0.2rem 0.5rem', borderRadius: '6px',
                      fontSize: '0.7rem',
                      background: i === guidedIdx ? '#FEF3C7' : (guidedIdx > i ? '#DCFCE7' : 'var(--bg2)'),
                      borderLeft: '3px solid ' + (i === guidedIdx ? '#F59E0B' : 'transparent'),
                    }}>
                      {s.notation}
                    </div>
                  ))}
                </div>
                {EDGELOC_GUIDED_STEPS.map((s, i) => (
                  <p key={i} style={{
                    fontSize: '0.78rem', color: i === guidedIdx ? 'var(--ink)' : 'var(--muted)',
                    fontWeight: i === guidedIdx ? 600 : 400,
                    marginBottom: '0.2rem',
                  }}>{i + 1}. {s.text}</p>
                ))}
                {guidedIdx >= EDGELOC_GUIDED_STEPS.length - 1 && (
                  <>
                    <div style={{
                      padding: '0.5rem 0.8rem', borderRadius: '6px',
                      background: '#DCFCE7', fontSize: '0.82rem', marginBottom: '0.6rem',
                    }}>
                      ✅ 三个黄色棱块顺时针轮换完成
                    </div>
                    <button className="btn btn-primary" onClick={() => setPhase('edgeloc-practice')}>
                      亲自试试 →
                    </button>
                  </>
                )}
              </>
            )}

            {/* 棱块归位 — 实操 */}
            {phase === 'edgeloc-practice' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  执行以下棱块置换：
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: '#FEF3C7', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '0.82rem', fontWeight: 700,
                  textAlign: 'center', color: '#B45309',
                }}>
                  {EDGELOC_SOLUTION_MOVES.map(moveToNotation).join(' → ')}
                </div>
                <div style={{ marginBottom: '1rem' }}>
                  <p style={{ fontSize: '0.75rem', color: 'var(--muted)', marginBottom: '0.4rem' }}>你已执行：</p>
                  <div style={{
                    padding: '0.4rem 0.8rem', borderRadius: '6px',
                    background: 'var(--bg2)', fontFamily: 'monospace',
                    fontSize: '0.82rem',
                    color: userNotations.length > 0 ? 'var(--accent)' : 'var(--muted)',
                  }}>
                    {userNotations.length > 0 ? userNotations.join(' → ') : '等待操作…'}
                  </div>
                </div>
                <button className="btn btn-outline" style={{ width: '100%' }} onClick={() => setRetryKey((k) => k + 1)}>
                  重置重试
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 角块归位（步骤6）— 介绍 */}
            {/* ================================================================ */}
            {phase === 'cornerloc-intro' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  黄色棱块已归位，现在把黄色角块移到正确位置。
                  这个操作是<strong>交换子 U R U' L' U R' U' L</strong>。
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: '#FEF3C7', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '0.85rem',
                  textAlign: 'center', color: '#B45309',
                }}>
                  U R U' L' U R' U' L
                </div>
                <ul style={{ fontSize: '0.82rem', color: 'var(--ink)', paddingLeft: '1.2rem', marginBottom: '1rem' }}>
                  <li style={{ marginBottom: '0.3rem' }}>这也是交换子结构：<strong>前半段 U R U' L'</strong> + <strong>后半段 U R' U' L</strong></li>
                  <li style={{ marginBottom: '0.3rem' }}>前半段把角块"搬出来"，后半段"换进去"</li>
                  <li>角块置换是<strong>奇置换</strong>（三个角块循环）</li>
                </ul>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <button className="btn btn-primary" onClick={() => setPhase('cornerloc-guided')}>
                    看引导演示
                  </button>
                  <button className="btn btn-outline" onClick={() => setPhase('cornerloc-practice')}>
                    直接实操
                  </button>
                </div>
              </>
            )}

            {/* 角块归位 — 引导 */}
            {phase === 'cornerloc-guided' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  观察角块交换的逐步动画：
                </p>
                <div style={{ display: 'flex', gap: '0.25rem', marginBottom: '0.8rem', flexWrap: 'wrap' }}>
                  {CORNERLOC_GUIDED_STEPS.map((s, i) => (
                    <div key={i} style={{
                      padding: '0.2rem 0.5rem', borderRadius: '6px',
                      fontSize: '0.7rem',
                      background: i === guidedIdx ? '#FEF3C7' : (guidedIdx > i ? '#DCFCE7' : 'var(--bg2)'),
                      borderLeft: '3px solid ' + (i === guidedIdx ? '#F59E0B' : 'transparent'),
                    }}>
                      {s.notation}
                    </div>
                  ))}
                </div>
                {CORNERLOC_GUIDED_STEPS.map((s, i) => (
                  <p key={i} style={{
                    fontSize: '0.78rem', color: i === guidedIdx ? 'var(--ink)' : 'var(--muted)',
                    fontWeight: i === guidedIdx ? 600 : 400,
                    marginBottom: '0.2rem',
                  }}>{i + 1}. {s.text}</p>
                ))}
                {guidedIdx >= CORNERLOC_GUIDED_STEPS.length - 1 && (
                  <>
                    <div style={{
                      padding: '0.5rem 0.8rem', borderRadius: '6px',
                      background: '#DCFCE7', fontSize: '0.82rem', marginBottom: '0.6rem',
                    }}>
                      ✅ 三个角块互换位置完成
                    </div>
                    <button className="btn btn-primary" onClick={() => setPhase('cornerloc-practice')}>
                      亲自试试 →
                    </button>
                  </>
                )}
              </>
            )}

            {/* 角块归位 — 实操 */}
            {phase === 'cornerloc-practice' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  执行以下角块交换：
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: '#FEF3C7', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '0.82rem', fontWeight: 700,
                  textAlign: 'center', color: '#B45309',
                }}>
                  {CORNERLOC_SOLUTION_MOVES.map(moveToNotation).join(' → ')}
                </div>
                <div style={{ marginBottom: '1rem' }}>
                  <p style={{ fontSize: '0.75rem', color: 'var(--muted)', marginBottom: '0.4rem' }}>你已执行：</p>
                  <div style={{
                    padding: '0.4rem 0.8rem', borderRadius: '6px',
                    background: 'var(--bg2)', fontFamily: 'monospace',
                    fontSize: '0.82rem',
                    color: userNotations.length > 0 ? 'var(--accent)' : 'var(--muted)',
                  }}>
                    {userNotations.length > 0 ? userNotations.join(' → ') : '等待操作…'}
                  </div>
                </div>
                <button className="btn btn-outline" style={{ width: '100%' }} onClick={() => setRetryKey((k) => k + 1)}>
                  重置重试
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 翻黄角（步骤7）— 介绍 */}
            {/* ================================================================ */}
            {phase === 'orient-intro' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  所有块都在正确位置，只剩黄色角块的朝向需要翻转。
                  使用经典的 <strong>Sune</strong>：R U R' U R U2 R'。
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: '#FEF3C7', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '0.85rem',
                  textAlign: 'center', color: '#B45309',
                }}>
                  R U R' U R U2 R'
                </div>
                <ul style={{ fontSize: '0.82rem', color: 'var(--ink)', paddingLeft: '1.2rem', marginBottom: '1rem' }}>
                  <li style={{ marginBottom: '0.3rem' }}>Sune 是<strong>3-cycle</strong>——每次翻转一个角块</li>
                  <li style={{ marginBottom: '0.3rem' }}>U2 = 两个连续 90° 旋转，<strong>不是</strong>矩阵平方</li>
                  <li>重复执行 Sune 即可翻正所有黄角，魔方完成！</li>
                </ul>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <button className="btn btn-primary" onClick={() => setPhase('orient-guided')}>
                    看引导演示
                  </button>
                  <button className="btn btn-outline" onClick={() => setPhase('orient-practice')}>
                    直接实操
                  </button>
                </div>
              </>
            )}

            {/* 翻黄角 — 引导 */}
            {phase === 'orient-guided' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  观察 Sune 的逐步操作：
                </p>
                <div style={{ display: 'flex', gap: '0.25rem', marginBottom: '0.8rem', flexWrap: 'wrap' }}>
                  {ORIENT_GUIDED_STEPS.map((s, i) => (
                    <div key={i} style={{
                      padding: '0.2rem 0.5rem', borderRadius: '6px',
                      fontSize: '0.7rem',
                      background: i === guidedIdx ? '#FEF3C7' : (guidedIdx > i ? '#DCFCE7' : 'var(--bg2)'),
                      borderLeft: '3px solid ' + (i === guidedIdx ? '#F59E0B' : 'transparent'),
                    }}>
                      {s.notation}
                    </div>
                  ))}
                </div>
                {ORIENT_GUIDED_STEPS.map((s, i) => (
                  <p key={i} style={{
                    fontSize: '0.78rem', color: i === guidedIdx ? 'var(--ink)' : 'var(--muted)',
                    fontWeight: i === guidedIdx ? 600 : 400,
                    marginBottom: '0.2rem',
                  }}>{i + 1}. {s.text}</p>
                ))}
                {guidedIdx >= ORIENT_GUIDED_STEPS.length - 1 && (
                  <>
                    <div style={{
                      padding: '0.5rem 0.8rem', borderRadius: '6px',
                      background: '#DCFCE7', fontSize: '0.82rem', marginBottom: '0.6rem',
                    }}>
                      ✅ 一个子角翻正！魔方可继续重复直至全部完成
                    </div>
                    <button className="btn btn-primary" onClick={() => setPhase('orient-practice')}>
                      亲自试试 →
                    </button>
                  </>
                )}
              </>
            )}

            {/* 翻黄角 — 实操 */}
            {phase === 'orient-practice' && (
              <>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.8rem' }}>
                  执行 Sune 翻转黄色角块：
                </p>
                <div style={{
                  padding: '0.6rem 1rem', marginBottom: '1rem',
                  background: '#FEF3C7', borderRadius: '8px',
                  fontFamily: 'monospace', fontSize: '0.82rem', fontWeight: 700,
                  textAlign: 'center', color: '#B45309',
                }}>
                  {ORIENT_SOLUTION_MOVES.map(moveToNotation).join(' → ')}
                </div>
                <div style={{ marginBottom: '1rem' }}>
                  <p style={{ fontSize: '0.75rem', color: 'var(--muted)', marginBottom: '0.4rem' }}>你已执行：</p>
                  <div style={{
                    padding: '0.4rem 0.8rem', borderRadius: '6px',
                    background: 'var(--bg2)', fontFamily: 'monospace',
                    fontSize: '0.82rem',
                    color: userNotations.length > 0 ? 'var(--accent)' : 'var(--muted)',
                  }}>
                    {userNotations.length > 0 ? userNotations.join(' → ') : '等待操作…'}
                  </div>
                </div>
                <button className="btn btn-outline" style={{ width: '100%' }} onClick={() => setRetryKey((k) => k + 1)}>
                  重置重试
                </button>
              </>
            )}

            {/* ================================================================ */}
            {/* 全部完成 */}
            {/* ================================================================ */}
            {phase === 'done' && (
              <>
                {starVisible && (
                  <div style={{ textAlign: 'center', marginBottom: '1rem' }}>
                    <span style={{ fontSize: '3rem' }}>🎉</span>
                    <p style={{ fontSize: '1.2rem', fontWeight: 700, color: 'var(--accent)', marginTop: '0.5rem' }}>
                      全部完成！
                    </p>
                  </div>
                )}
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.5rem' }}>
                  你成功完成了七步骤全部复原：白色十字 → 白色角块（逆序列法则） → 中层棱块（共轭变换） → 黄色十字（交换子） → 棱块归位（置换群） → 角块归位（交换子）→ 翻黄角（Sune）。
                </p>
                <p style={{ fontSize: '0.85rem', color: 'var(--ink2)', marginBottom: '0.5rem' }}>
                  <strong>你已经亲身体验了线代→群论的完整渐进教学闭环</strong>：
                  打开→操作→关上（交换子）、逆序列、乘法不可交换（Sune 的效果与顺序相关）、
                  置换循环、奇置换与偶置换——全部通过实际操作！
                </p>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <Link to="/chapter/solve" className="btn btn-outline" style={{ flex: 1, textAlign: 'center', textDecoration: 'none' }}>
                    回到第6节
                  </Link>
                  <Link to="/playground" className="btn btn-primary" style={{ flex: 1, textAlign: 'center', textDecoration: 'none' }}>
                    巩固练习 →
                  </Link>
                </div>
              </>
            )}
          </div>
        </div>

        {/* 右：魔方 */}
        <div style={{ width: '420px', flexShrink: 0 }}>
          <div style={{
            height: '420px', borderRadius: 'var(--radius)',
            overflow: 'hidden', border: '1px solid var(--rule)',
          }}>
            <Cube3DView ref={cubeRef} />
          </div>
        </div>
      </div>
    </div>
  )
}
