/* Generated by Trae Work */
import type { ReactNode } from 'react';

/**
 * AnalogyNote 组件 Props
 */
interface AnalogyNoteProps {
  /** 提示内容（支持任意 React 节点） */
  children: ReactNode;
}

/**
 * 类比说明提示条组件
 * 浅蓝底色 + 左边框，用于数学概念与魔方的类比解说
 * 样式由全局 .analogy-note 类控制
 */
export default function AnalogyNote({ children }: AnalogyNoteProps) {
  return (
    <div className="analogy-note">
      {/* 前置图标：灯泡代表类比提示 */}
      <span role="img" aria-label="提示">
        💡
      </span>
      {/* 提示正文 */}
      <span>{children}</span>
    </div>
  );
}
