/* Generated by Trae Work */

/**
 * MatrixDisplay 组件 Props
 */
interface MatrixDisplayProps {
  /** 二维数组，表示矩阵的每一行（兼容 data 和 rows） */
  data?: (number | string)[][]
  rows?: (number | string)[][]
  /** 矩阵的可选标签（显示在矩阵上方） */
  label?: string
}

/**
 * 矩阵显示组件
 * 使用 CSS 的 .matrix 左右边框 + 中间等宽数字渲染
 * 标记: 纯 CSS 实现，无需依赖
 */
export default function MatrixDisplay({ data, rows: rowsProp, label }: MatrixDisplayProps) {
  const rows = data ?? rowsProp
  if (!rows || rows.length === 0) {
    return <span style={{ color: 'var(--muted)', fontSize: '0.85rem' }}>[空矩阵]</span>
  }

  return (
    <div className="matrix-wrapper">
      {/* 矩阵标签 */}
      {label && <span className="matrix-label">{label}</span>}
      {/* 矩阵本体 */}
      <div className="matrix">
        {rows.map((row, ri) => (
          <div key={ri} className="mrow">
            {row.map((val, ci) => (
              <span key={ci}>{val}</span>
            ))}
          </div>
        ))}
      </div>
    </div>
  )
}
