/* Generated by Trae Work */
import { NavLink } from 'react-router-dom';

/**
 * 导航项配置：路径 + 中文标题
 * 所有页面共享同一套导航，保证一致性
 */
const navLinks = [
  { to: '/chapter/intro', label: '入门科普' },
  { to: '/chapter/compose', label: '核心章节' },
  { to: '/playground', label: '实操训练' },
  { to: '/archive', label: '数学档案馆' },
];

/**
 * 顶部导航栏组件
 * 毛玻璃效果，固定顶部
 * 只使用内联样式和 index.css 已有的 CSS 变量，不依赖 Tailwind
 */
export default function Navbar() {
  const linkBase: React.CSSProperties = {
    fontSize: '0.85rem',
    fontWeight: 500,
    textDecoration: 'none',
    color: 'var(--ink2)',
    transition: 'color 0.2s',
  };

  return (
    <nav
      style={{
        position: 'fixed', top: 0, left: 0, right: 0, zIndex: 100,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        height: '3.5rem', padding: '0 1.5rem',
        background: 'rgba(255,255,255,0.7)',
        backdropFilter: 'blur(12px)',
        WebkitBackdropFilter: 'blur(12px)',
        borderBottom: '1px solid var(--rule)',
      }}
    >
      <NavLink
        to="/"
        style={{
          fontSize: '1.1rem', fontWeight: 700,
          letterSpacing: '-0.02em',
          color: 'var(--ink)',
          textDecoration: 'none',
        }}
      >
        Cube × Math
      </NavLink>

      <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem' }}>
        {navLinks.map(({ to, label }) => (
          <NavLink
            key={to}
            to={to}
            end
            style={({ isActive }) => ({
              ...linkBase,
              color: isActive ? 'var(--ink)' : 'var(--ink2)',
              position: 'relative',
              ...(isActive ? {
                fontWeight: 600,
              } : {}),
            })}
          >
            {label}
          </NavLink>
        ))}
      </div>
    </nav>
  );
}
