/* Generated by Trae Work — 从旧项目 InteractiveCube.tsx 适配 */
import { useEffect, useRef, useState, useCallback, forwardRef, useImperativeHandle } from 'react'
import * as THREE from 'three'
import type { Cubie, CubieFaceColors, FaceColor, Axis, Move, Layer, Direction } from '../../types/cube'
import { FACE_COLOR_MAP } from '../../types/cube'
import { createSolvedCube, applyMove, parseMoveNotation, scrambleCube } from '../../lib/cubeLogic'
import { useCubeStore } from '../../store/cubeStore'

/* ===== 常量定义 ===== */
/** 魔方内面颜色（不可见面） */
const INTERIOR_COLOR = '#d0d5dd'
/** 面之间接缝颜色 */
const EDGE_COLOR = '#888888'
/** 转动动画时长（毫秒） */
const ANIMATION_DURATION = 280

/** 六个面的渲染顺序 */
const FACE_ORDER: (keyof CubieFaceColors)[] = ['right', 'left', 'up', 'down', 'front', 'back']

/** 面法向量，用于射线检测判断鼠标悬停的是哪个面 */
const FACE_NORMALS: Record<string, THREE.Vector3> = {
  R: new THREE.Vector3(1, 0, 0),
  L: new THREE.Vector3(-1, 0, 0),
  U: new THREE.Vector3(0, 1, 0),
  D: new THREE.Vector3(0, -1, 0),
  F: new THREE.Vector3(0, 0, 1),
  B: new THREE.Vector3(0, 0, -1),
}

/** 面 → 旋转轴映射 */
const FACE_AXIS: Record<string, Axis> = { R: 'x', L: 'x', U: 'y', D: 'y', F: 'z', B: 'z' }
/** 面 → 层号映射 */
const FACE_LAYER: Record<string, number> = { R: 1, L: -1, U: 1, D: -1, F: 1, B: -1 }

/* ===== 类型定义 ===== */
/** 转动动画状态 */
interface AnimationState {
  pivot: THREE.Object3D
  cubieGroups: THREE.Group[]
  targetAngle: number
  startTime: number
  axis: Axis
  move: Move
  /** 动画完成后是否跳过 store 同步（撤销时用） */
  skipStore?: boolean
}

/** Cube3DView 对外暴露的操控方法 */
export interface Cube3DViewHandle {
  /** 执行一步旋转变换（记法，如 "R"、"U'"），会同步写入 store */
  executeMove: (notation: string) => void
  /** 执行一步撤销逆操作（仅动画，不写 store） */
  undoMove: (notation: string) => void
  /** 打乱魔方 n 步 */
  scramble: (n?: number) => void
  /** 重置为还原状态 */
  reset: () => void
  /** 是否正在播放动画 */
  isAnimating: () => boolean
}

/* ===== 方块创建辅助函数 ===== */
/** 根据 Cubie 的面颜色创建 6 个面的材质数组 */
function createCubieMaterials(cubie: Cubie): THREE.MeshStandardMaterial[] {
  return FACE_ORDER.map((face) => {
    const colorKey: FaceColor | null = cubie.colors[face]
    const colorHex = colorKey ? FACE_COLOR_MAP[colorKey] : INTERIOR_COLOR
    return new THREE.MeshStandardMaterial({ color: new THREE.Color(colorHex), roughness: 0.7, metalness: 0.0 })
  })
}

/** 创建一个方块 Group（BoxGeometry + EdgesGeometry） */
function createCubieGroup(cubie: Cubie, pos: [number, number, number], s: number, cs: number): THREE.Group {
  const g = new THREE.Group()
  g.position.set(pos[0] * s, pos[1] * s, pos[2] * s)
  const geo = new THREE.BoxGeometry(cs, cs, cs)
  const mesh = new THREE.Mesh(geo, createCubieMaterials(cubie))
  g.add(mesh)
  const eg = new THREE.EdgesGeometry(geo)
  g.add(new THREE.LineSegments(eg, new THREE.LineBasicMaterial({ color: EDGE_COLOR })))
  return g
}

/** 批量创建所有方块的 Group */
function buildCubieGroups(cubies: Cubie[], s: number, cs: number): THREE.Group[] {
  return cubies.map((c) => createCubieGroup(c, c.position, s, cs))
}

/** 销毁方块 Group 的几何体和材质（仅组件卸载时调用） */
function disposeCubieGroup(g: THREE.Group): void {
  g.traverse((child) => {
    if (child instanceof THREE.Mesh || child instanceof THREE.LineSegments) {
      child.geometry.dispose()
      const mat = child.material
      if (Array.isArray(mat)) mat.forEach((m) => m.dispose())
      else if (mat) mat.dispose()
    }
  })
}

/** 更新已有 Group 的 MeshStandardMaterial 颜色（不销毁几何体/材质，避免 WebGL 资源竞争） */
function updateCubieGroupColors(g: THREE.Group, cubie: Cubie): void {
  g.traverse((child) => {
    if (child instanceof THREE.Mesh) {
      const mats = child.material
      if (Array.isArray(mats)) {
        FACE_ORDER.forEach((face, i) => {
          const colorKey: FaceColor | null = cubie.colors[face]
          const hex = colorKey ? FACE_COLOR_MAP[colorKey] : INTERIOR_COLOR
          if (i < mats.length && mats[i] instanceof THREE.MeshStandardMaterial) {
            mats[i].color.set(hex)
          }
        })
      }
    }
  })
}

/** Cube3DView 组件 props */
interface Cube3DViewProps {
  /** 是否禁用 store 写入（仅作纯视觉演示，不污染全局 history） */
  disableStore?: boolean
}

/* ===== 组件 ===== */
const Cube3DView = forwardRef<Cube3DViewHandle, Cube3DViewProps>(function Cube3DView({ disableStore } = {}, ref) {
  /* ---- Refs ---- */
  const containerRef = useRef<HTMLDivElement>(null)
  const sceneRef = useRef<THREE.Scene | null>(null)
  const cameraRef = useRef<THREE.PerspectiveCamera | null>(null)
  const rendererRef = useRef<THREE.WebGLRenderer | null>(null)
  const cubieGroupsRef = useRef<THREE.Group[]>([])
  /** 魔方数据副本 — Three.js 动画需要直接读写，所以用 ref 而不是 store */
  const cubieDataRef = useRef<Cubie[]>(createSolvedCube())
  const animRef = useRef<AnimationState | null>(null)
  const animIdRef = useRef<number>(0)
  const raycasterRef = useRef(new THREE.Raycaster())
  const mouseRef = useRef(new THREE.Vector2())

  /* ---- 本地状态 ---- */
  const [isAnimating, setIsAnimating] = useState(false)
  const [hoveredFace, setHoveredFace] = useState<string | null>(null)

  /* ---- Zustand store ---- */
  const storeScramble = useCubeStore((s) => s.scramble)
  const storeReset = useCubeStore((s) => s.reset)
  const storeApplyMove = useCubeStore((s) => s.applySingleMove)

  /* ---- 轨道控制参数 ---- */
  const orbitRef = useRef({
    theta: Math.atan2(5, 5),
    phi: Math.asin(4 / Math.sqrt(66)),
    radius: Math.sqrt(66),
    isDragging: false,
    lastMouse: { x: 0, y: 0 },
  })

  /* ---- 计算间距 ---- */
  const spacing = 1.0 / 3
  const cubieSizeVal = spacing * 0.85

  /* ---- 获取某一层的方块 Groups ---- */
  const getLayerCubieGroups = useCallback((axis: Axis, layer: number): THREE.Group[] => {
    const sel: THREE.Group[] = []
    const th = spacing * 0.6
    const tc = layer * spacing
    const pos = new THREE.Vector3()
    for (const g of cubieGroupsRef.current) {
      g.getWorldPosition(pos)
      const c = axis === 'x' ? pos.x : axis === 'y' ? pos.y : pos.z
      if (Math.abs(c - tc) < th) sel.push(g)
    }
    return sel
  }, [spacing])

  /* ---- 刷新方块（完全重建：先 dispose 旧 Group，再创建新 Group） ---- */
  const refreshCubies = useCallback((scene: THREE.Scene) => {
    // 先收集旧 Groups 并暂停渲染（避免 dispose 时 GPU 还在用）
    const old = cubieGroupsRef.current
    cubieGroupsRef.current = []
    // 创建新 Groups
    const ng = buildCubieGroups(cubieDataRef.current, spacing, cubieSizeVal)
    for (const g of ng) scene.add(g)
    cubieGroupsRef.current = ng
    // 延迟一帧后再 dispose 旧 Groups，确保 GPU 已切换渲染新 Groups
    if (old.length > 0) {
      const toDispose = [...old]
      // 先从场景移除旧 Groups（让 GPU 不再引用）
      for (const g of toDispose) scene.remove(g)
      // 在下一帧 dispose 几何体和材质
      requestAnimationFrame(() => {
        for (const g of toDispose) disposeCubieGroup(g)
      })
    }
  }, [spacing, cubieSizeVal])

  /* ---- 更新相机位置 ---- */
  const updateCamera = useCallback(() => {
    const c = cameraRef.current
    if (!c) return
    const { theta, phi, radius } = orbitRef.current
    c.position.set(
      radius * Math.cos(phi) * Math.sin(theta),
      radius * Math.sin(phi),
      radius * Math.cos(phi) * Math.cos(theta),
    )
    c.lookAt(0, 0, 0)
  }, [])

  /* ---- 执行转动动画 ---- */
  const executeMoveAnimated = useCallback((axis: Axis, layer: number, direction: number, scene: THREE.Scene, skipStore?: boolean) => {
    if (animRef.current) return
    const selected = getLayerCubieGroups(axis, layer)
    if (selected.length === 0) return
    const pivot = new THREE.Object3D()
    scene.add(pivot)
    for (const g of selected) pivot.attach(g)
    const angle = (Math.PI / 2) * direction
    animRef.current = {
      pivot, cubieGroups: selected, targetAngle: angle, startTime: performance.now(),
      axis,
      move: { axis, layer: layer as Layer, direction: direction as Direction },
      skipStore,
    }
  }, [getLayerCubieGroups])

  const executeMove = useCallback((notation: string) => {
    if (animRef.current || isAnimating) return
    const scene = sceneRef.current
    if (!scene) return
    const move = parseMoveNotation(notation)
    executeMoveAnimated(move.axis, move.layer, move.direction, scene, !!disableStore)
    setIsAnimating(true)
  }, [isAnimating, executeMoveAnimated, disableStore])

  /** 撤销用：执行逆操作动画但不写 store */
  const undoMove = useCallback((notation: string) => {
    if (animRef.current || isAnimating) return
    const scene = sceneRef.current
    if (!scene) return
    const move = parseMoveNotation(notation)
    executeMoveAnimated(move.axis, move.layer, move.direction, scene, true)
    setIsAnimating(true)
  }, [isAnimating, executeMoveAnimated])

  /* ---- 对外暴露操控 API ---- */
  useImperativeHandle(ref, () => ({
    executeMove: (notation: string) => {
      executeMove(notation)
    },
    undoMove: (notation: string) => {
      undoMove(notation)
    },
    scramble: (n: number = 20) => {
      const scene = sceneRef.current
      if (!scene || animRef.current) return
      const { cubies, moves } = scrambleCube(createSolvedCube(), n)
      cubieDataRef.current = cubies
      refreshCubies(scene)
      // 演示模式不写 store
      if (!disableStore) storeScramble({ cubies, moves })
    },
    reset: () => {
      const scene = sceneRef.current
      if (!scene || animRef.current) return
      cubieDataRef.current = createSolvedCube()
      refreshCubies(scene)
      if (!disableStore) storeReset()
    },
    isAnimating: () => isAnimating,
  }), [executeMove, refreshCubies, storeScramble, storeReset, isAnimating, disableStore])

  /* ---- 场景初始化 ---- */
  useEffect(() => {
    const container = containerRef.current
    if (!container) return

    /* 场景 */
    const scene = new THREE.Scene()
    scene.background = new THREE.Color('#f5f7fa')
    sceneRef.current = scene

    /* 相机 */
    const camera = new THREE.PerspectiveCamera(
      45, container.clientWidth / Math.max(container.clientHeight, 1), 0.1, 100,
    )
    const o = orbitRef.current
    camera.position.set(
      o.radius * Math.cos(o.phi) * Math.sin(o.theta),
      o.radius * Math.sin(o.phi),
      o.radius * Math.cos(o.phi) * Math.cos(o.theta),
    )
    camera.lookAt(0, 0, 0)
    camera.zoom = 2       // 视觉放大2倍，不改变几何体
    camera.updateProjectionMatrix()
    cameraRef.current = camera

    /* 渲染器 */
    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: false })
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2))
    renderer.setSize(container.clientWidth, container.clientHeight)
    container.appendChild(renderer.domElement)
    rendererRef.current = renderer

    /* 灯光 */
    const al = new THREE.AmbientLight(0x888899, 1.0)
    scene.add(al)
    const dl = new THREE.DirectionalLight(0xffffff, 1.8)
    dl.position.set(5, 10, 5)
    scene.add(dl)
    const dl2 = new THREE.DirectionalLight(0xffffff, 1.0)
    dl2.position.set(-3, 2, -4)
    scene.add(dl2)
    const dl3 = new THREE.DirectionalLight(0xffffff, 0.5)
    dl3.position.set(0, -5, 8)
    scene.add(dl3)

    /* 方块 */
    const ig = buildCubieGroups(cubieDataRef.current, spacing, cubieSizeVal)
    for (const g of ig) scene.add(g)
    cubieGroupsRef.current = ig

    /* 收集所有方块 Mesh 用于射线检测 */
    const allCubies: THREE.Mesh[] = []
    ig.forEach(g => g.traverse(child => { if (child instanceof THREE.Mesh) allCubies.push(child) }))

    /* 检测鼠标指向的面 */
    const detectFace = (clientX: number, clientY: number): string | null => {
      const rect = renderer.domElement.getBoundingClientRect()
      mouseRef.current.x = ((clientX - rect.left) / rect.width) * 2 - 1
      mouseRef.current.y = -((clientY - rect.top) / rect.height) * 2 + 1
      raycasterRef.current.setFromCamera(mouseRef.current, camera)
      const intersects = raycasterRef.current.intersectObjects(allCubies)
      if (intersects.length === 0) return null
      const faceNormal = intersects[0].face!.normal.clone()
      faceNormal.transformDirection(intersects[0].object.matrixWorld)
      let best = ''
      let bestDot = -Infinity
      for (const [key, normal] of Object.entries(FACE_NORMALS)) {
        const dot = faceNormal.dot(normal)
        if (dot > bestDot && dot > 0.5) { bestDot = dot; best = key }
      }
      return best || null
    }

    /* ---- 鼠标事件：左键逆时针 / 右键顺时针 ---- */
    const onMouseDown = (e: MouseEvent) => {
      if (animRef.current) return
      if (e.button !== 0 && e.button !== 2) return // 只处理左键(0)和右键(2)

      const face = detectFace(e.clientX, e.clientY)
      if (face) {
        const axis = FACE_AXIS[face]
        const layer = FACE_LAYER[face]
        // 左键 = 逆时针（方向 = layer），右键 = 顺时针（方向 = -layer）
        const dir = e.button === 0 ? layer : -layer
        executeMoveAnimated(axis, layer, dir, sceneRef.current!, false)
        setIsAnimating(true)
        return
      }
      // 空白处：左键拖拽旋转视角，右键忽略
      if (e.button === 0) {
        o.isDragging = true
        o.lastMouse = { x: e.clientX, y: e.clientY }
      }
    }

    const onMouseMove = (e: MouseEvent) => {
      if (!o.isDragging) {
        if (!animRef.current) {
          const face = detectFace(e.clientX, e.clientY)
          setHoveredFace(face)
          container.style.cursor = face ? 'pointer' : ''
        }
        return
      }
      const dx = e.clientX - o.lastMouse.x
      const dy = e.clientY - o.lastMouse.y
      o.lastMouse = { x: e.clientX, y: e.clientY }
      o.theta -= dx * 0.005
      o.phi += dy * 0.005
      o.phi = Math.max(-Math.PI / 2 + 0.1, Math.min(Math.PI / 2 - 0.1, o.phi))
      updateCamera()
    }

    const onMouseUp = () => {
      o.isDragging = false
    }

    /** 阻止右键默认菜单 */
    const onContextMenu = (e: MouseEvent) => {
      e.preventDefault()
    }

    const onWheel = (e: WheelEvent) => {
      e.preventDefault()
      o.radius += e.deltaY * 0.01 * (o.radius / 8)
      o.radius = Math.max(3, Math.min(20, o.radius))
      updateCamera()
    }

    /* ---- 触摸事件：点击面=顺时针，空白拖拽=旋转视角 ---- */
    let touchFace: string | null = null
    const onTouchStart = (e: TouchEvent) => {
      if (animRef.current || e.touches.length !== 1) return
      touchFace = detectFace(e.touches[0].clientX, e.touches[0].clientY)
      if (touchFace) return // 点击面，等 touchend 处理
      o.isDragging = true
      o.lastMouse = { x: e.touches[0].clientX, y: e.touches[0].clientY }
    }

    const onTouchMove = (e: TouchEvent) => {
      if (!o.isDragging || e.touches.length !== 1) return
      e.preventDefault()
      const dx = e.touches[0].clientX - o.lastMouse.x
      const dy = e.touches[0].clientY - o.lastMouse.y
      o.lastMouse = { x: e.touches[0].clientX, y: e.touches[0].clientY }
      o.theta -= dx * 0.005
      o.phi += dy * 0.005
      o.phi = Math.max(-Math.PI / 2 + 0.1, Math.min(Math.PI / 2 - 0.1, o.phi))
      updateCamera()
    }

    const onTouchEnd = () => {
      if (touchFace && !o.isDragging) {
        const axis = FACE_AXIS[touchFace]
        const layer = FACE_LAYER[touchFace]
        // 触摸默认顺时针（方向 = -layer）
        const dir = -layer
        executeMoveAnimated(axis, layer, dir, sceneRef.current!, false)
        setIsAnimating(true)
      }
      touchFace = null
      o.isDragging = false
    }

    /* ---- 绑定事件 ---- */
    renderer.domElement.addEventListener('mousedown', onMouseDown)
    window.addEventListener('mousemove', onMouseMove)
    window.addEventListener('mouseup', onMouseUp)
    renderer.domElement.addEventListener('contextmenu', onContextMenu)
    renderer.domElement.addEventListener('wheel', onWheel, { passive: false })
    renderer.domElement.addEventListener('touchstart', onTouchStart, { passive: false })
    renderer.domElement.addEventListener('touchmove', onTouchMove, { passive: false })
    window.addEventListener('touchend', onTouchEnd)

    const onResize = () => {
      const { clientWidth: cw, clientHeight: ch } = container
      camera.aspect = cw / Math.max(ch, 1)
      camera.updateProjectionMatrix()
      renderer.setSize(cw, ch)
    }
    window.addEventListener('resize', onResize)

    /* ---- 渲染循环 ---- */
    const render = (time: number) => {
      const anim = animRef.current
      if (anim) {
        const et = time - anim.startTime
        let t = Math.min(et / ANIMATION_DURATION, 1)
        t = 1 - (1 - t) * (1 - t) // ease-out
        const ca = anim.targetAngle * t
        anim.pivot.rotation.set(0, 0, 0)
        if (anim.axis === 'x') anim.pivot.rotation.x = ca
        else if (anim.axis === 'y') anim.pivot.rotation.y = ca
        else anim.pivot.rotation.z = ca
        if (et >= ANIMATION_DURATION) {
          // 动画完成：用 applyMove 计算新的 cubie 数据
          const newCubies = applyMove(cubieDataRef.current, anim.move)
          cubieDataRef.current = newCubies
          // 直接把每个 involved group 的 position 设为新 cubie 数据的位置，rotation 重置为 identity
          // 这样 group 的 local 坐标系与世界坐标轴对齐，FACE_ORDER 对应正确的面
          const s = spacing
          for (const g of anim.cubieGroups) {
            const wp = new THREE.Vector3()
            g.getWorldPosition(wp)
            // 找到 newCubies 中位置最接近 wp 的 cubie
            let bestIdx = -1
            let bestDist = Infinity
            for (let ci = 0; ci < newCubies.length; ci++) {
              const cp = newCubies[ci].position
              const dx = wp.x - cp[0] * s
              const dy = wp.y - cp[1] * s
              const dz = wp.z - cp[2] * s
              const d = dx * dx + dy * dy + dz * dz
              if (d < bestDist) { bestDist = d; bestIdx = ci }
            }
            if (bestIdx >= 0) {
              const c = newCubies[bestIdx]
              scene.attach(g) // 先 detach from pivot
              g.rotation.set(0, 0, 0)
              g.position.set(c.position[0] * s, c.position[1] * s, c.position[2] * s)
              updateCubieGroupColors(g, c)
            }
          }
          scene.remove(anim.pivot)
          anim.pivot.clear()
            // 同步到 Zustand store（撤销动画跳过，因为 undo 已在外部处理）
            if (!anim.skipStore) {
              storeApplyMove(anim.move)
            }
            animRef.current = null
          setIsAnimating(false)
        }
      }
      renderer.render(scene, camera)
      animIdRef.current = requestAnimationFrame(render)
    }
    animIdRef.current = requestAnimationFrame(render)

    /* ---- 清理 ---- */
    return () => {
      cancelAnimationFrame(animIdRef.current)
      renderer.domElement.removeEventListener('mousedown', onMouseDown)
      window.removeEventListener('mousemove', onMouseMove)
      window.removeEventListener('mouseup', onMouseUp)
      renderer.domElement.removeEventListener('contextmenu', onContextMenu)
      renderer.domElement.removeEventListener('wheel', onWheel)
      renderer.domElement.removeEventListener('touchstart', onTouchStart)
      renderer.domElement.removeEventListener('touchmove', onTouchMove)
      window.removeEventListener('touchend', onTouchEnd)
      window.removeEventListener('resize', onResize)
      if (animRef.current) { scene.remove(animRef.current.pivot); animRef.current.pivot.clear() }
      for (const g of cubieGroupsRef.current) { disposeCubieGroup(g); scene.remove(g) }
      cubieGroupsRef.current = []
      scene.traverse((obj) => {
        if (obj instanceof THREE.Mesh || obj instanceof THREE.LineSegments) {
          obj.geometry.dispose()
          const mat = obj.material
          if (Array.isArray(mat)) mat.forEach(m => m.dispose())
          else if (mat) mat.dispose()
        }
      })
      scene.clear()
      renderer.dispose()
      if (container.contains(renderer.domElement)) container.removeChild(renderer.domElement)
    }
  }, []) // 仅 mount 时执行一次

  return (
    <div style={{ display: 'flex', flexDirection: 'column', width: '100%', flex: 1, minHeight: '300px' }}>
      {/* 3D 画布容器 */}
      <div
        ref={containerRef}
        style={{
          position: 'relative', width: '100%', flex: 1, minHeight: 0,
          borderRadius: '12px', overflow: 'hidden',
          background: '#f5f7fa', border: '1px solid var(--rule, #e2e5ea)',
        }}
      >
        {/* 悬停提示：显示当前面 + 左右键操作方式 */}
        {hoveredFace && (
          <div style={{
            position: 'absolute', top: '8px', left: '8px', zIndex: 10,
            padding: '4px 10px', borderRadius: '6px',
            background: 'rgba(37,99,235,0.9)', color: '#fff',
            fontSize: '11px', fontFamily: 'monospace',
            lineHeight: 1.5,
          }}>
            <div>{hoveredFace}面</div>
            <div style={{ fontSize: '10px', opacity: 0.85 }}>
              左键↺逆时针 | 右键↻顺时针
            </div>
          </div>
        )}
      </div>
      {/* 操作提示 */}
      <div style={{
        textAlign: 'center', paddingTop: '6px',
        fontSize: '11px', color: 'var(--ink2, #5f6368)',
      }}>
        左键点击面 = 逆时针 | 右键点击面 = 顺时针 | 空白拖拽 = 旋转视角
      </div>
    </div>
  )
})

export default Cube3DView
