/* Generated by Trae Work */
import { Routes, Route } from 'react-router-dom'
import Layout from './components/Layout'
import Landing from './pages/Landing'
import Chapter from './pages/Chapter'
import Playground from './pages/Playground'
import Archive from './pages/Archive'
import Tutorial from './pages/Tutorial'

/** 应用根组件：Layout 包裹所有子路由 */
export default function App() {
  return (
    <Routes>
      <Route element={<Layout />}>
        <Route path="/" element={<Landing />} />
        <Route path="/chapter/:id" element={<Chapter />} />
        <Route path="/playground" element={<Playground />} />
        <Route path="/archive" element={<Archive />} />
      <Route path="/tutorial" element={<Tutorial />} />
      </Route>
    </Routes>
  )
}
